### ISSUE TITLE
TiShadow seems to have issues loading modules

### ISSUE THREAD

**Issue by rickycheers** [dbankier/TiShadow#143]
Hi, I hope you can help me with this issue.

I'm getting the following errors when the bundle is sent to the devices and tries to start it.

```
[DEBUG] Bundle requested.
[INFO] [android, 4.1.2, 192.168.15.21] Unpacking new bundle: iListMobile
[INFO] [android, 4.1.2, 192.168.15.21] Previous bundle closed.
[INFO] [android, 4.1.2, 192.168.15.21] Requiring: appdata-private:///iListMobile/alloy
[DEBUG] [android, 4.1.2, 192.168.15.21] Native module:alloy/underscore
[ERROR] [android, 4.1.2, 192.168.15.21]
Type: Error
Message: Requested module not found
File: ti
Line: /module.js
At:   Module.require
[ERROR] [android, 4.1.2, 192.168.15.21]
Type: TypeError
Message: Cannot read property '_' of undefined
File: /alloy.js
Line: 19
At:   eval at custom_require
[ERROR] [android, 4.1.2, 192.168.15.21]
Type: TypeError
Message: Cannot read property '_' of undefined
File: api/PlatformRequire.js
Line: 57
At:   eval at <anonymous>
[INFO] [android, 4.1.2, 192.168.15.21] iListMobile launched.
```

First I though it might be my version of TiShadow, I was using 1.3.2 and upgraded to 2.0.1. I also upgraded TiShadow app with `tishadow app --upgrade -d dir/to/tishadowapp` then I reinstalled the app into my device and tried again.

All this seemed to start happening after I tried to clear cache with `tishadow clear`after that I was never able to run my app again into TiShadow

Node version: 0.10.13
Alloy version: 1.2.2
TiShadow version: 2.0.1

It's worth mentioning that if I build my application directly into a device, I don't get those error messages and it runs as expected.

Thanks in advance!

**Comment by pedrotnascimento** [comment]
I always have this problem, my version is 2.8.8, I don't think it's solved by upgrading!
