### ISSUE TITLE
[ERROR] Appify Failed.

### ISSUE THREAD

**Issue by ggoidin** [dbankier/TiShadow#196]
Hello, 

I m a Windows 7 user and each time i try to build using the command :

ti build --shadow -p android -T device

the process ends with the following error : 

[ERROR] Appify Failed.

I m using ti 3.2.0.GA with latest tishadow (from gitHub).
I attached a screenshot of the error.

![appify](https://f.cloud.github.com/assets/6418501/1942233/0d13bf52-7f96-11e3-8320-fc93eaa8b051.png)

**Comment by pedrotnascimento** [comment]
If running:
appc ti build -p android --shadow   
or 
appc ti build -p android --appify

doesn't create the build\appify directory (which was my case)

try running  in root directory

tishadow appify -d build\appify -P android

It worked for me.
