### ISSUE TITLE
Genymotion: INSTALL_FAILED_MISSING_SHARED_LIBRARY

### ISSUE THREAD

**Issue by slash-84** [dbankier/TiShadow#272]
Hi,
since /api/Includes.js came back in 2.5.5 i get this error when trying to install the app in Genymotion or any AVD without Google APIs.

Commenting lines
https://github.com/dbankier/TiShadow/blob/master/app/Resources/api/Includes.js#L58-L59

will fix the problem

**Comment by sg552** [comment]
I am wondering is there an option for us to install Google Apps when creating virtual devices using Genymotion?  
refer to: http://stackoverflow.com/a/20636252/445908

**Comment by FokkeZB** [comment]
As it says there as well... this has not been available anymore for more then a year now.

**Comment by sg552** [comment]
@FokkeZB  got it, thanks!
