### ISSUE TITLE
Ti shadow not working

### ISSUE THREAD

**Issue by tmrhalwagy** [dbankier/TiShadow#313]
Hi,

Tishadow is a great product, I am anxious to use it but struggling to make it work
wit titanium SDK 3.2.3.GA
I have installed Tishadow

as follows

sudo npm install -g tishadow --unsafe-perm

mkdir ~/tishadowapp && tishadow app -d ~/tishadowapp

and running it like this

titanium build -p android -T emulator --shadow

(its genymotion emulator, tried with iOS simulator and real android device)

got the same result with all of them

, its not working properly , after I connect to my tishadow localhost server
and compile my alloy project and send the bundle to the Tishadow 
alloy compile -c platform=android
and
tishadow run (or tishadow run -u)
the tishadow mobile app disconnects and when i connect I see two icons one for "ts" and one for my alloy project

I got same result with google play tishadow android app

help will be highly appreciated i spent days with this

**Comment by dwgeneral** [comment]
I ran "  ti build -p android --device-id "192.168.56.101:5555  --shadow "  (its genymotion emulator)
and I got the error
[ERROR] Invalid Android device "192.168.56.101:5555"

**Comment by dbankier** [comment]
@dwgeneral, the error message is accurate.
Please learn how to use the titanium cli without tishadow first
