### ISSUE TITLE
Images no longer showing when run through Tishadow

### ISSUE THREAD

**Issue by shealan** [dbankier/TiShadow#385]
I had everything working well but suddenly images are not showing properly. The only thing I can think of that has changed is the installation of the 3.5.0 Beta SDK.

Is anyone else having problems with this beta SDK installed?

**Comment by jvandijk** [comment]
Hi @dbankier while running the latest nightly build I still run into an issue with the same kinda form. When selecting photos using openPhotoGallery on the success callback the event.media blob is missing when using TiShadow. Might it be related to the 'resolved' issue or TiShadow?

**Comment by dbankier** [comment]
ts doesn't mangle with openPhotoGallery and I doubt it's related to this issue.
