### ISSUE TITLE
Cannot get tishadow to work

### ISSUE THREAD

**Issue by jfbomber** [dbankier/TiShadow#386]
When I run the command
ti build -p ios -F iphone --tishadow

[INFO]  Building App...
[INFO]  Starting TiShadow server
[ERROR] TiShadow Server exited.

--- More info
Running 3.4.0 on Mac OSX - Yosemite

Also if build the tishadowapp and the run tishadow server, then try to connect to the app using localhost it doesnt work
![ios simulator screen shot jan 3 2015 1 47 33 am](https://cloud.githubusercontent.com/assets/1092988/5601991/80d30caa-92ea-11e4-9839-31d49eb390f3.png)

if I do the following :
ts server

then run :
ti build -p ios --appify

It says "Could not find all required Titanium Modules:"
[ERROR] id: yy.tidynamicfont version: 0.2.0 platform: iphone deploy-type: development
[ERROR] id: yy.logcatcher version: 0.2.0 platform: iphone deploy-type: development
[ERROR] id: ti.compression version: 1.1.1 platform: iphone deploy-type: development

**Comment by jfbomber** [comment]
if I do the following : 
ts server

then run : 
ti build -p ios --appify

It says "Could not find all required Titanium Modules:"
[ERROR]    id: yy.tidynamicfont	 version: 0.2.0	 platform: iphone	 deploy-type: development
[ERROR]    id: yy.logcatcher	 version: 0.2.0	 platform: iphone	 deploy-type: development
[ERROR]    id: ti.compression	 version: 1.1.1	 platform: iphone	 deploy-type: development

**Comment by dbankier** [comment]
check if anything else is running on port 3000. You can check the default port that tishadow runs on with, e.g. `tishadow config -p 3001`.

Also the minsdk for the new modules that support 64-bit archs is 3.4.1 which is why it can't find the modules.

**Comment by jfbomber** [comment]
When I try to build it with 3.4.1 it tells me

[ERROR] Unable to compile a 3.4.1.GA project with Titanium SDK 3.4.0.GA
[ERROR] To build this application, set the <sdk-version> in the tiapp.xml to the current Titaniums SDK: 3.4.0.GA

**Comment by dbankier** [comment]
change the sdk version in your tiapp.xml to 3.4.1.GA

**Comment by jfbomber** [comment]
Thats when the error is thrown. I am sure that the error has something to do with my machine because it doesn't seem to be consistent, thanks for your help.

**Comment by dbankier** [comment]
`ti sdk install 3.4.1.GA`
and/or
`ti sdk select 3.4.1.GA`
