### ISSUE TITLE
Provide mechanism to initialize spec environment

### ISSUE THREAD

**Issue by milgner** [dbankier/TiShadow#387]
## User story

When an application is started regularly, the `alloy.js` is run and can be used to initialize the environment. Thus it can be used to set globals or load modules that are used throughout the app.

But when running `tishadow spec`, that file is not executed and there is no way to set up an environment - such as loading Alloy for starters - so that the code under test runs with an environment like the regular one.

## Workaround
Something like `if (!Alloy) {  Alloy = require("/alloy"); }` can work in some cases. Yet that renders the modules not test-agnostic anymore. Also it's not possible to set global variables like - for example - the database name in `Alloy.Globals` from outside the module under test.

**Comment by dbankier** [comment]
Thanks for the clear issue.

Can you try adding this to the top of your spec and see if that gives you what you want.

~~~
__p.eval('var Alloy = require("alloy"), _ = Alloy._, Backbone = Alloy.Backbone;');
~~~

I think it might. If that works then I'll automatically inject it to the specs of Alloy projects.
