### ISSUE TITLE
Fonts smaller in TiShadow compared to app

### ISSUE THREAD

**Issue by m1ga** [dbankier/TiShadow#389]
This is the app in TiShadow
![fonts_tishadow](https://cloud.githubusercontent.com/assets/4334997/5693276/25ba8000-9916-11e4-946c-3c1211728fa7.png)

and this when I compile it straight to the phone:
![fonts_app](https://cloud.githubusercontent.com/assets/4334997/5693303/195b2c50-9917-11e4-94aa-0ba30f3c8cce.png)

tss
~~~
"Label": {
    width: Ti.UI.SIZE,
    height: Ti.UI.SIZE,
    color: "#fff",
    touchEnabled:false
}

".title":{
     font:{fontSize:18,fontWeight:"bold"},color:"#e52834"
}

"#text":{
	left:15,right:15,top:10
}

"#tf_place":{
	width:200
}

"#btn_place":{
	width:200
}

~~~

defaultunit is dp (tiapp.xml). How can I change TiShadow to use the same dpi?

Nexus 4
Ti SDK 3.4.1
TiShadow 2.7.2

**Comment by bitfabrikken** [comment]
Try removing the defaultunit line completely.

**Comment by m1ga** [comment]
nothing changed. Did a "tishadow clear && tishadow run" afterwards

**Comment by m1ga** [comment]
ah, the tishadow app itself didn't have a defaultunit, so I set it there to dp and compiled the tishadow app again. Now it looks fine. Shouldn't
~~~
<property name="ti.ui.defaultunit" type="string">dp</property>
~~~
be in the default tishadow tiapp.xml since it is in the default titanium app tiapp.xml?

**Comment by bitfabrikken** [comment]
Sorry typed that earlier reply on mobile - I meant you should either a) remove defaultunit from your standalone app's tiapp.xml (not the tishadow's tiapp.xml) or b) add the defaultunit line to tishadow's tiapp.xml

The difference you're seeing is likely because the two apps aren't the same - so e.g. your main app thinks it must add "dp" after your units, but tishadow doesn't, thus defaulting to some other unit.

**Comment by bitfabrikken** [comment]
Good you figured it out :) I agree it should be standard as this probably confuses some people. But it's up to dbankier :)

**Comment by m1ga** [comment]
thanks for the explanation :+1:  I'll close the issue

**Comment by m1ga** [comment]
add a pull request https://github.com/dbankier/TiShadow/pull/390 so its quicker to add it :)
