### ISSUE TITLE
i18n String are not translated with Titanium SDK 3.5.0GA

### ISSUE THREAD

**Issue by christoferw** [dbankier/TiShadow#393]
After switching to the 3.5 SDK i18n String are no longer translated. If I run the same app without "--shadow" the i18n translation works fine.

**Comment by dbankier** [comment]
Fixed and will push a new version (2.7.4) to npm soon (having issues at the moment).
As an FYI, 3.5.0.GA started preventing me from overriding the L global.

Thanks for pointing out the issue.

**Comment by dbankier** [comment]
getting the `npm ERR! registry error parsing json` from npm. npm must be having issues. Will try and publish to npm later. You can always install straight from master if you want.

**Comment by christoferw** [comment]
Thank you very much. I tested it with the latest master version. i18n translation is working again with tishadow
