### ISSUE TITLE
3.5.0.GA and files

### ISSUE THREAD

**Issue by kopiro** [dbankier/TiShadow#394]
It seems that with 3.5.0.GA there are some issues with Filesystem.

For example:

```js
Ti.Filesystem.getFile(Ti.Filesystem.applicationSupportDirectory).createDirectory();
```

and

```js
Ti.Filesystem.getFile(Ti.Filesystem.applicationSupportDirectory).exists() == false
```

**Comment by dbankier** [comment]
Is this tishadow specific or even without?

**Comment by kopiro** [comment]
Tishadow specific.
Same code without Tishadow say `true`

**Comment by dbankier** [comment]
replicated. fix on the way.
was this working pre-3.5.0?

**Comment by kopiro** [comment]
Oh yes, until 3.4.1.GA

If can help you, I think that is a problem with spaces.

**Comment by dbankier** [comment]
fixed now. 3.5.0 keeps breaking things....

**Comment by dbankier** [comment]
just pushing a new version to npm

**Comment by kopiro** [comment]
Oh, thanks! :dancer:

**Comment by jvandijk** [comment]
hey @dbankier this also seems to solve the issue I had with the photoGallery picker when using tishadow express. Could you confirm that?
