### ISSUE TITLE
64bit issues

### ISSUE THREAD

**Issue by bitfabrikken** [dbankier/TiShadow#395]
Trying to compile TiShadow for iOS Simulator, iPhone 6, iOS 8.1 gives the following errors:

[ERROR] :  Script Error Couldn't find module: ti.compression for architecture: x86_64
[ERROR] :  Script Error Module "/api/TiShadow" failed to leave a valid exports object
[ERROR] :  Script Error Module "/ui/StartScreen" failed to leave a valid exports object
[ERROR] :  ErrorController is up. ABORTING showing of modal controller
[ERROR] :  ErrorController is up. ABORTING showing of modal controller

TiShadow 2.5.6 downloaded via "sudo npm install tishadow" yesterday.
Titanium SDK 3.5.0.GA, 
Titanium Studio build 3.4.1.201410281727, 
OS X Yosemite 10.10.1, 
Xcode 6.1.1

Any ideas? I can see the ti.compression module hasn't been updated on GitHub for 2 years..

**Comment by dbankier** [comment]
Do a clean build. You might need to regenerate the tishadow app.  The updated 64 bit modules are already part of the release.

**Comment by bitfabrikken** [comment]
@dbankier: Something else is going on then - I just did a fresh "ts app -d ts", imported the ts project and set the project nature to mobile. Then ran from Studio with iPhone 6 iOS 8.1 as target - I still get the red error screen with the above mentioned errors. Do you have any what could be causing this, or how I can get past it?

**Comment by dbankier** [comment]
just did a clean build and it worked fine. double check the sdk in the project is set to 3.5.0

**Comment by bitfabrikken** [comment]
Sorry for the trouble @dbankier - seems I had to use -g flag with npm for it to overwrite TiShadow 2.5.6 with 2.5.7 - it works like a charm now :)

**Comment by dbankier** [comment]
No problem

**Comment by jericho1ne** [comment]
Still getting "Couldn't find module: ti.compression for architecture: x86_64 " when doing an iPhone6 build.  Works fine for iPhone5 or 5s.  What could be the cause?

**Comment by dbankier** [comment]
@jericho1ne, make sure you are using the latest version of tishadow and using TISDK > =3.5.0
