### ISSUE TITLE
Localization on 2.7.5

### ISSUE THREAD

**Issue by adampax** [dbankier/TiShadow#396]
Hi David,

I just updated from 2.7.0 to 2.7.5 and find that locale strings aren't being displayed on iOS or Android.  I just have en strings, and tried running with and without `--locale en`.  

Additional notes: on 2.7.5 I tried building the tishadow app with Ti 3.5.0.GA and 3.4.0.  I've since returned to 2.7.0 and am running on 3.4.0.

**Comment by nuno** [comment]
#393 is not fixed for you @adampax ?

**Comment by adampax** [comment]
@nuno Didn't see that ticket, thanks for pointing it out.  it appears that no it doesn't fix for me.  I'm using `titleid` properties in Alloy views if that matters.

**Comment by nuno** [comment]
Hey @adampax, np any time. Wondering if you update the app? 
tishadow app -d ~/tishadowapp --upgrade

**Comment by adampax** [comment]
@nuno I think so, but may have used -u flag.  Not sure if that matters, I'll run through it again to be sure

**Comment by m1ga** [comment]
Having the same with a Android app at the moment. Looks like the XML titleid's are not translated. When I log L("save") it will display the correct output in the console. Also strings from js files are set correct.

**Comment by dbankier** [comment]
sorry @adampax, missed that one use case. fixed now

**Comment by adampax** [comment]
Thanks @dbankier
