### ISSUE TITLE
connect ETIMEDOUT error when updating

### ISSUE THREAD

**Issue by shodanuk** [dbankier/TiShadow#398]
I keep getting the following when tishadow tries to push updates to an app:

    [ERROR] Error: connect ETIMEDOUT

This occurs regardless of method used. Ie. `--shadow`, `--appify` or `ts server` & `ts run -u`.

The app installs & runs initially but any attempted updates result in the above error.

This has occurred for me on both tishadow 2.7.5 & 2.7.6 and Ti SDK 3.4.1 & 3.5.0.

I'm using OSX Yosemite and deploying to an iOS 8.1 simulator.

**Comment by shodanuk** [comment]
Has anyone got any thoughts on this? Is there are more information I can provide that will help debugging?

**Comment by dbankier** [comment]
What is the output of 'ts config'?
Can you access the web interface from your computer? From your sim? Any firewalls? Does the sim connect? How big is the bundle? What version node?

**Comment by shodanuk** [comment]
Hi David,

Thanks for the reply. As requested:

Output of `ts config` :

```
{
    "isWatching": false,
    "host": "10.0.1.10"
}
```

"Can you access the web interface from your computer?"
Yes

"From your sim?"
Yes

"Any firewalls?"
Yes, although I have disabled it with no effect

"Does the sim connect?"
Sim can connect to internet. App deploys to sim initially, as do other apps I've worked on.

"﻿﻿﻿How big is the bundle?"
The .app bundle is 28.9Mb

"What version node?"
0.10.29

Thanks.

**Comment by shodanuk** [comment]
Ah hang on - that host address doesn't look right. Let me check that out before you look any further into it

**Comment by shodanuk** [comment]
Yep, that was it. I've recently moved home and my network IP addresses have changed. I must have set the one listed above as a default at some point and forgotten about it.

Thanks again for your help, @dbankier.
