### ISSUE TITLE
Jasmine: Test createController?

### ISSUE THREAD

**Issue by m1ga** [dbankier/TiShadow#399]
How can I use jasmine to test if a new controller gets created in an alloy project?

In my code I have (index.js)
~~~
Alloy.createController("request");
~~~
and it will create a new window. Now I want to check if the window is open and want to access its elements.

my test for index.js:
~~~
// Create a test suite
describe("test1", function() {
    var Alloy = require("alloy");
    var $;
    beforeEach(function() {
        $ = Alloy.createController("index");
    });
 
    describe("can create and destroy", function() {
        it("show request window", function() {
            $.__views.btn_requests.fireEvent("click");
            waits(500);
            runs(function () {
                //$ = Alloy.createController("requests"); // will create a 2nd window
                //expect(??).toBe(true);    // what do I need to check
            });
        });
    });
});
~~~

it will click the button and the button will run the createController code => the window opens. But now I can't access its elements and don't know how to test if the window is visible. When I run 
~~~
$ = Alloy.createController("requests");
~~~
in my spec it will create a second window in my app.

Is it the wrong approach I'm trying? How would I use tishadow to test this?

**Comment by dbankier** [comment]
This is more of a mocha/testing question than a TS issue. Closing for now.
