### ISSUE TITLE
Just want to say: YOU are AWESOME

### ISSUE THREAD

**Issue by caspahouzer** [dbankier/TiShadow#401]
Thanks for this great piece of work. You saved me hours and days of compiling time!

**Comment by cdrx** [comment]
+1 - I cant thank you enough

**Comment by nuno** [comment]
David, I cant thank you enough too!!!
You are awesome!

**Comment by yomybaby** [comment]
+1 👍

**Comment by m1ga** [comment]
:+1:

**Comment by dbankier** [comment]
Thanks for raising the issue and everyone's comments.
Sounds like it relates to performance and will hopefully be sorted once test coverage improves.
Closing it for now. 

:smile:

**Comment by FokkeZB** [comment]
:+1:
