### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'ifile.read().text')

### ISSUE THREAD

**Issue by vdesdoigts** [dbankier/TiShadow#402]
Hello, I have this error on my iOS emulator logs when i launch an app with TiShadow.
Have you any idea where it comes from?
Thanks.

**Comment by dbankier** [comment]
what version of tishadow and titanium?

**Comment by vdesdoigts** [comment]
Oh... You made me think of updating my TiCli, it was on 3.4.1, in 3.6.0-dev it's working.
Thanks!
