### ISSUE TITLE
TiShadow start which IP ?

### ISSUE THREAD

**Issue by nazrdogan** [dbankier/TiShadow#404]
its not issue .but I want to give idea .When I prompt tishadow server on my machine . TiShadow start at localhost:3000  but my IP change when I go different place with my pc. Could you do TiShadow start at  my ip  like  192.168.1.xx .I know how to learn my IP .but This way will be easy. 

Thanks for TiShadow .you are saving people time :)

**Comment by yomybaby** [comment]
You can use `--network-interface`.
After run `ts config --network-interface en0`, tishadow and appify use ip address of `en0`.

In my macbook pro, `en0` is wifi network.

Also, you can use `-n` instead of `--network-interface`. 
```
ts config -n en0
```

**Comment by nazrdogan** [comment]
![phonegap-developer-app-pairing](https://cloud.githubusercontent.com/assets/1672303/6108832/f0c38542-b07e-11e4-9cb7-c7ef735b431b.png)


I mean I want to seee my ip adress like this .not localhost:3000 . Sorry for my english. if TiShadow have this feature ı dont know.

**Comment by nazrdogan** [comment]
Thank you David :+1:
