### ISSUE TITLE
 Node v0.12.0 TiShadow installation problem.

### ISSUE THREAD

**Issue by nazrdogan** [dbankier/TiShadow#405]
I upgraded  Node.js v0.12.0  and try to install or upgrade new version of  TiShadow .its gives me this error. 
![node 0 12 0](https://cloud.githubusercontent.com/assets/1672303/6123394/aab9a450-b10a-11e4-9ac7-f990f74f11bd.png)

**Comment by dbankier** [comment]
I don't think titanium support 0.12.x yet, so I'm going to hold off on this.

**Comment by dbankier** [comment]
just installed fine with 0.12.x.
search around a bit about that error, e.g. http://creoge.blogspot.com.au/2013/04/my-nodejs-socketio-struggle.html?spref=tw
