### ISSUE TITLE
Runtime Error in DensityAssets.js

### ISSUE THREAD

**Issue by wpccolorblind** [dbankier/TiShadow#407]
Tried a --shadow on one of my apps so I can start using tishadow to develop with it.  Fairly familiar with tishadow now from the past month or so, but I'm getting this very odd issue on android.

Error:
{
  "message": "Uncaught TypeError: Object function (from, to) {\n    var rest = this.slice((to || from) + 1 || this.length);\n    this.length = 0 > from ? this.length + from : from;\n    return this.push.apply(this, rest);\n} has no method 'replace'",
  "lineOffset": 69,
  "line": 1,
  "title": "Runtime Error",
  "lineSource": "r(n in density_folders)if(s=r.replace(\"%FOLDER%\",density_folders[n].replace(\"%",
  "sourceName": "api/DensityAssets.js"
}

Code:
var newImage = Ti.UI.createImageView( {
	image: {any image url is reproducing this}
} )

container.add( newImage )

This same code works great when I just test it in my index.js file and some others.  However, the same code in other files just won't work, even when I reference the same container.  This is because the error comes on the line that actually creates the image.

If I do a try catch around it, I catch an exception but it's completely empty.

I'm stumped after several hours of investigating this and minifying the example to reproduce...

Not quite sure what the code in tishadow around the error is doing, but obviously the file variable is not what the code expects and it just assumes it's a string, replace is called, and thus the exception.

Anyone seen anything like this before?

**Comment by dbankier** [comment]
Haven't seen this. Can you share a sample app that can reproduce the issue?
Also what versions of Ti, TiShadow, and Android?

**Comment by wpccolorblind** [comment]
shadow 2.7.6
android 4.4.4
ti 3.5.0.GA

Have been unable to get a minimized app that reproduces it as of yet.  This code is buried deep in some nested view/controllers which seems to be what is affecting it.  When I take it up levels I'm able to create an ImageView using a remote image just fine.

I can also confirm that this only happens for remote images.

Looked at the tishadow code around where this bug occurs and can't really tell without a bit more intimate knowledge of tishadow.  Any guesses why this code is even running for a remote image?  Looks like it's android specific code for copying assets from density specific folders, which seems to me like has  nothing to do with what I'm doing (simplest type of ImageView loading a remote url).

Thanks @dbankier

**Comment by dbankier** [comment]
Looks like an issue with your code. Is the remote url string, looks like you are passing a function.

**Comment by wpccolorblind** [comment]
Definition not a function, it's a string.  Hard coding any URL image from the internet does it.  However, a few levels up in the view/controller that hosts this view/controller it works.  I'm sure there is going to be a workaround that I can implement, but shouldn't the most basic ImageView creation work anywhere?

Don't think I mentioned this either, but it works if I build and run the app without tishadow.

**Comment by bitfabrikken** [comment]
Also getting the same error.
Have upgraded from TS 2.7.5 to 2.8.1.
Titanium SDK 3.5.0.GA.
Any way to solve this? I needs my TiShadow :)

**Comment by bitfabrikken** [comment]
Did some digging. I, and probably wpccolorblind, do not use the /android/images folder - instead I use /pix, which I've gotten used to. There's no 9 patch images there or resolution specific things.
I think that's what the code chokes on currently - not being able to find what it's expecting.
I made a small fix, that seems to work for me: https://github.com/dbankier/TiShadow/compare/master...bitfabrikken:patch-2
