### ISSUE TITLE
Shadow for the TiShadow icon?

### ISSUE THREAD

**Issue by m1ga** [dbankier/TiShadow#409]
i've used a vectorize version of the png, but it looks nice with this hipster 45° shadow:

![path3119](https://cloud.githubusercontent.com/assets/4334997/6176101/53400f5e-b2fc-11e4-8ae0-4c5519b0fb58.png)

**Comment by dbankier** [comment]
Thanks for the effort.
I'll put this to a vote.

**Comment by dbankier** [comment]
Thanks for the effort, but doesn't sound like there is much enthusiasm about updated in the logo.
Closing for now.
