### ISSUE TITLE
Exclude some files of changes-watch

### ISSUE THREAD

**Issue by Pyreweb** [dbankier/TiShadow#410]
Hi,
I'd like to not monitor some files for changes, as they are compiled when the app build;
I use STSS in my app, which compile stss files to tss.
When I try to use tiShadow, it compiled, detected changes to somes files (the tss from stss), then compiled again, then detected changes, and so, until it freezed my computer ;)

An option to exclude selected files or folders exists ? Or another way to get this to work ?

*I've seen [JAST](https://github.com/dbankier/JAST) but from afar it looks like a lot of changes for a project that's in the middle of it's ending;*

**Comment by sg552** [comment]
hi Pyreweb, what do you think of this pull request: 

https://github.com/dbankier/TiShadow/pull/408

It allows you to change your watch-files by extension.

**Comment by dbankier** [comment]
@Pyreweb, yep this issue has already been lodged. I reopened the PR, but it isn't ready to merge yet. Watch that PR. Closing this issue.

**Comment by Pyreweb** [comment]
Yep, exactly what I want, I'll watch this :+1:

**Comment by dbankier** [comment]
Just pushed this commit: https://github.com/dbankier/TiShadow/commit/cac7251d754d8592a6d2aec276a950af8c482da0
It gives you what you want.

You can add globs of what you want to exclude using, e.g.  `ts config --watch-exclude app/**/*.tss`

**Comment by Pyreweb** [comment]
Work like a charm, thanks !

Just a smally little point, what we have to type is `ts config --watch-exclude "app/**/*.tss"` (quote the path)
