### ISSUE TITLE
how to auto-load app/alloy.js ? 

### ISSUE THREAD

**Issue by sg552** [dbankier/TiShadow#412]
hi,

    I found that TiShadow could not auto-load app/alloy.js where I defined some global variables. Nether require absolute path nor require related path works.

    Is there anything I can do for this? or did I do something wrong? 

thanks, 
Siwei

**Comment by dbankier** [comment]
Is this for specs?
If so - see this issue: https://github.com/dbankier/TiShadow/issues/387

**Comment by sg552** [comment]
Yes! you are right!  thanks !!!
