### ISSUE TITLE
run spec takes too long time. let's give it some text illustration to show on the console.

### ISSUE THREAD

**Issue by sg552** [dbankier/TiShadow#413]
Hi dbankier,

  My titanium project increased to 16MB, and I found it took me about 18 seconds to Connect and then unpack the bundle 

````bash
[INFO] 850 file(s) bundled.
[INFO] BUNDLE sent.
// from here,  
[INFO] [android, 4.1.2, 192.168.1.102] Connected
[INFO] [android, 4.1.2, 192.168.1.102] Unpacking new bundle: HappyStock
// end here, takes me 18 seconds.  ( real android device) 
[INFO] [android, 4.1.2, 192.168.1.102] Requiring: appdata-private://HappyStock/spec//index_spec.js
````

  what about let give it an indicator showing what is happening during this 18 seconds time so that I won't lose my focus and know everything is working well? 

thanks, 
Siwei

**Comment by dbankier** [comment]
You can use the `--update` flag on `spec` that _should_ only push the modified files.

**Comment by sg552** [comment]
great! thanks! I will try it~
