### ISSUE TITLE
<property name="ti.ui.defaultunit"> doesn't work

### ISSUE THREAD

**Issue by MarioRossi00** [dbankier/TiShadow#416]
Hi, and thanks for your great product. I used it for months without problem. Now it shows a strange behavior never had before: I usually  set the tiapp.xml  ti.ui.defaultunit in px for my reasons and I wish to continue to work in this way. Now, when I set width or height of a Window or a View or other it seems that on TiShadow client side these dimensions are doubled. In other words: if I have a device (S3) with 720x1280 resolution I can't use 720 or 1280 but 360 and 640 (the half size) otherwise I can't see properly. The compiled app on Genymotion or real device  works fine.
I use TiShadow vers. 2.8.0  (also 2.7 had the same issue)
Ti.SDK 3.5.0 and 3.4.1
Thanks for all.
MR

**Comment by dbankier** [comment]
are you using the `tishadow app` or the express way using the `--shadow` flag?

**Comment by MarioRossi00** [comment]
Thanks for your reply. I use the tishadow app on my S3. I tried also the tishadow app on Genymotion. I have compiled it with TiShadow version 2.7.1 and vers. 2.8.0 but the problem not solved. Previously the tishadow app worked perfectly with <property name="ti.ui.defaultunit">. What can be happend? I'm making some kind of mistake? Bye

**Comment by dbankier** [comment]
If you are using the container app, you need to set the default unit in the tiapp of that app.
