### ISSUE TITLE
Can't use inspector function!

### ISSUE THREAD

**Issue by winsonet** [dbankier/TiShadow#419]
when I use the inspector in chrome, I always get the following error:

in ios:
0:11:40 [ERROR] [iphone, 8.1, 192.168.1.102] ReferenceError: Can't find variable: me

in android:
0:21:08 [ERROR] [android, 4.1.1, 10.0.3.15] <br/>Type: ReferenceError Message: me is not defined File: api/PlatformRequire.js Line: 175 At: eval at <anonymous>

any ideas? 

my TiShadow version is 2.8 and titanium sdk is 3.5, the app just deploy to simulator

thanks!

**Comment by dbankier** [comment]
Hi. You need to use the `--inspector` flag when using `ts run`.
It is turned off by default due to the overhead.

**Comment by winsonet** [comment]
Oh, thank you!!
