### ISSUE TITLE
tishadow in retina mode

### ISSUE THREAD

**Issue by gurmukhp** [dbankier/TiShadow#420]
Hi there

How am I able to preview my apps in tall retina mode? I have built the app in CLI using the following command:

- titanium build -p ios --retina --tall -T device

However the app still loads in 'large' mode, this doesnt seem to be iphone 6 optimised? I've also tried to build through Titanium to my phone and still having no luck. Am I able to view my app in iphone 6 optimised mode?

**Comment by dbankier** [comment]
what version of tishadow?

**Comment by dbankier** [comment]
@3x assets are there so should be working...
