### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by caspahouzer** [dbankier/TiShadow#425]
Hello,

on installing TiShadow I got the following error

~~~
sudo npm i tishadow -g
npm WARN engine tishadow@2.8.1: wanted: {"node":"0.10.x"} (current: {"node":"0.12.1","npm":"2.5.1"})
\
> ws@0.4.32 install /usr/local/lib/node_modules/tishadow/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)
~~~

Not more. Any hints?

**Comment by shodanuk** [comment]
npm WARN engine tishadow@2.8.1: wanted: {"node":"0.10.x"} (current: {"node":"0.12.1","npm":"2.5.1"})

TiShadow requires Node 0.10.x. You're running 0.12.1. Check out NVM if you need to manage multiple versions of Node.

**Comment by caspahouzer** [comment]
Thanks

**Comment by caspahouzer** [comment]
Sorry pal, but that wasn't it completely

~~~
sebastian-MacBook-Pro:sebastian sebastian$ node -v
v0.10.38
sebastian-MacBook-Pro:sebastian sebastian$ sudo npm i tishadow -g

> ws@0.4.32 install /usr/local/lib/node_modules/tishadow/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

~~~

**Comment by shodanuk** [comment]
I wonder if the first failed attempt left some rubbish behind. 

You could try:

    $ npm remove tishadow -g
    $ npm i tishadow -g

Try and avoid sudo, if you don't absolutely need it

**Comment by caspahouzer** [comment]
unfortunately that brings the same result :(

**Comment by shodanuk** [comment]
Anything helpful in builderror.log ?

**Comment by caspahouzer** [comment]
Sorry, but where to find this log?

**Comment by caspahouzer** [comment]
After an hour I tried again to install and it worked. I don't know why...

**Comment by shodanuk** [comment]
Ah it might have something to do with the Github outages today. Glad you got it sorted

**Comment by caspahouzer** [comment]
That was my thought too
