### ISSUE TITLE
Can I use TiShadow with Appcelerator CLI?

### ISSUE THREAD

**Issue by appkery** [dbankier/TiShadow#427]
Hello.
I tried to use it with Appcelerator CLI and below is the error message I got.
Is it possible to use it with Appcelerator CLI?
Because I don't want to download the whole Studio just for LiveView.
Thank you.
```
> node cli/tishadow express


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

npm ERR! tishadow@2.8.1 postinstall: `node cli/tishadow express`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the tishadow@2.8.1 postinstall script.
npm ERR! This is most likely a problem with the tishadow package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node cli/tishadow express
npm ERR! You can get their info via:
npm ERR!     npm owner ls tishadow
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.3.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "tishadow"
npm ERR! cwd /usr/local/n/versions/node
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by dbankier** [comment]
did you install like this: 
`sudo npm install -g tishadow --unsafe-perm`

**Comment by nazrdogan** [comment]
You need to install Titanium CLI 

<code>
npm install titanium -g
</code>

**Comment by dbankier** [comment]
will be trying appc cli soon...

**Comment by ulizama** [comment]
I'm having the same issues with Appcelerator CLI.

**Comment by dbankier** [comment]
@ulizama, is your problem with installing or using express?
If installing, try `ts express` to install it.
If it is using it, it might be because `ti` and `alloy` commands are not available in the new `appc` cli. (Which is annoying.)
Will need to `ts` able to detect what's installed.

**Comment by ulizama** [comment]
So, I wasn't able to install, I had to install titanium cli to be able to do so. But then, when running with appify it reports an Alloy syntax error, so it doesn't do the appify compile but it does compile the app, which runs without a problem, just without TiShadow support.

**Comment by dbankier** [comment]
If you install the ti cli and alloy cli it will work, but it won't be the appc ti and appc alloy. Bit of a confusing mess. I need to make the commands configurable to support appc ti and appc alloy.
In the meantime you could alias `ti` and `alloy` to point to the `appc` ones.
Still haven't looked at the new `appc` cli....

**Comment by dbankier** [comment]
Should be ok now. Can you install from master? If it works then I'll push a new version.

By default TiShadow uses the (free) `titanium` and `alloy` cli's under the hood. If you are using the (paid) `appc` cli then use the following command after installation:

```
$ ts config --use-appc-CLI
```

**Comment by FokkeZB** [comment]
@dbankier you could now also use http://npmjs.com/package/appc-compat to automatically select the right CLI.
