### ISSUE TITLE
Trouble Loading the application on Genymotion

### ISSUE THREAD

**Issue by jesalsangani** [dbankier/TiShadow#428]
I am having getting the following error while doing the build.

[ERROR] [android, 4.4.4, 10.0.3.15]  
Type: Error 
Message: Requires VIBRATE permission 
File: /lib/applicationWindow.js.js 
Line: 1 
At:   eval at custom_require 
[INFO] [android, 4.4.4, 10.0.3.15] Requiring: appdata-private://Concierge/styles.js
[ERROR] [android, 4.4.4, 10.0.3.15]  
Type: TypeError 
Message: undefined is not a function 
File: api/PlatformRequire.js 
Line: 1 
At:   eval at <anonymous> 

I have done follwing things:
1) Made sure there is a vibrate permission on tiapp.xml for tiappshadow server.
2) I have copied all the custom modules on tiappshadow resouces/android folder
3) I have copied styles.js at the root level.

I have researched both stackoverflow and appcelerator Q&A. 
Any direction is appreciated.

**Comment by nazrdogan** [comment]
did you try install android emulator or real device ?

**Comment by dbankier** [comment]
According to the logs, it looks like it was an issue with your code not TS.
