### ISSUE TITLE
Locale error "sUTF-8"

### ISSUE THREAD

**Issue by m1ga** [dbankier/TiShadow#430]
I'm using a weather service in my app which sends an ID (int) which can be translated to localized strings

In my app I use:

~~~
$.lbl_weather.text = L("s" + e.weather[0].id);
~~~

because I can't use just the integer as my i18n name ('ts run' won't complain but the compiled ti app does). But with this I'm receiving this error:

error:
~~~
[ERROR] [android, 5.0.1, 192.168.1.4] 
Type: Error
Message: sUTF-8
File: api/Localisation.js
Line: 1
At:   loadFile
~~~

i18n file looks like this:

~~~
<?xml version="s1.0" encoding="sUTF-8" ?>
<resources>
    <string name="s200">Gewitter mit leichtem Regen</string>
    <string name="s201">Gewitter mit Regen</string>
    <string name="s202">Gewitter mit starkem Regen</string>
    <string name="s210">leichte Gewitter</string>
    <string name="s211">Gewitter</string>
    <string name="s212">schwere Gewitter</string>
...
~~~

Building with ti works fine
Testing with ts produces an error

**Comment by dbankier** [comment]
did you work this on out? new lines at the beginning of the xml?

**Comment by m1ga** [comment]
I've uploaded a [testfile](http://migaweb.de/app.zip). 
When I compile it with TI is see:
~~~
[INFO]  Locale: de-DE
[INFO]  Lang: de
[INFO]  code: s802
[INFO]  translated: überwiegend bewölkt
~~~

in tishadow:
~~~
[INFO] [android, 4.4.4, 192.168.1.28] Locale: de-DE
[INFO] [android, 4.4.4, 192.168.1.28] Lang: de
[INFO] [android, 4.4.4, 192.168.1.28] code: s802
~~~

The error is not appearing but it won't translate the text. But I have another phone at the moment (Android 4.4.4 instead of 5.0). So not sure why the error disappeared but its showing the text.

Its receiving some test-weather data from openweather. If you call the API too often it will respond with an error message and won't show anything even not the s802 code. So don't call it too quickly :)

**Comment by dbankier** [comment]
You localisation file is wrong.

The first line reads:

~~~
<?xml version="s1.0" encoding="sUTF-8" ?>
~~~

when it should be:

~~~
<?xml version="1.0" encoding="UTF-8" ?>
~~~

**Comment by m1ga** [comment]
oh damn. Thanks. But still "ts run --locale en" shows the default phone language:
[INFO]  Locale: de-DE
[INFO]  Lang: de
[INFO]  code: s802

not en
