### ISSUE TITLE
Tishadow installation problem

### ISSUE THREAD

**Issue by alexgalvagno** [dbankier/TiShadow#431]
Hello,
I try to reinstall tishadow to my Mac after an upgrade, but the installation fails with the follow error.
Thank you.

> node cli/tishadow express

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

npm ERR! tishadow@2.8.1 postinstall: `node cli/tishadow express`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the tishadow@2.8.1 postinstall script.
npm ERR! This is most likely a problem with the tishadow package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node cli/tishadow express
npm ERR! You can get their info via:
npm ERR!     npm owner ls tishadow
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "tishadow" "--unsafe-perm"
npm ERR! cwd /Users/xxxxxx/Documents/Titanium_Studio_Workspace/Club Manager
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by nazrdogan** [comment]
<code>
$ sudo npm install -g tishadow --unsafe-perm
</code>

Did you try this ?

**Comment by alexgalvagno** [comment]
Yes I do. But the result is the same.

**Comment by nazrdogan** [comment]
https://github.com/dbankier/TiShadow/issues/421#issuecomment-84897103
Can you look at this ? it may help you

**Comment by alexgalvagno** [comment]
I try this:
$ npm i tishadow -g

but the result is this error.
npm ERR! Error: EACCES, mkdir '/usr/local/lib/node_modules/tishadow'
npm ERR!  { [Error: EACCES, mkdir '/usr/local/lib/node_modules/tishadow']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/tishadow',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/lib/node_modules/tishadow',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'Object.oncomplete (fs.js:108:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "i" "tishadow" "-g"
npm ERR! cwd /Users/giuseppedavidegivitta
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! path /usr/local/lib/node_modules/tishadow
npm ERR! fstream_path /usr/local/lib/node_modules/tishadow
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/usr/local/lib/node_modules/tishadow'
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53
npm ERR! fstream_stack Object.oncomplete (fs.js:108:15)
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/giuseppedavidegivitta/npm-debug.log
npm ERR! not ok code 0

I also verified my node version: 
$ node -v
v0.10.37

**Comment by nazrdogan** [comment]
did you try with sudo ? I think its about file permission .


<code> 
sudo npm i tishadow -g
</code>

**Comment by nazrdogan** [comment]
Issues Installing NPM packages
If you experience an issue installing any of the npm packages, try the following:

Check permissions. If you originally ran npm using sudo, you may need to change the ownership of the npm cache folder.
<code>
sudo chown -R <username> ~/.npmrc
</code>
On Windows, the npm cache defaults to npm-cache in the user's home directory.
Clear the npm package cache:
<code>
npm cache clean
</code>
Remove your .npmrc file.

**Comment by alexgalvagno** [comment]
I'm on Mac OS,
I have changed the owner these directory:

rwxr-xr-x   5 giuseppedavidegivitta  staff    170 24 Apr 11:07 .node-gyp
drwxr-xr-x   2 giuseppedavidegivitta  staff     68 24 Apr 11:27 .npm
drwxr-xr-x   3 giuseppedavidegivitta  staff    102 24 Apr 10:58 .nvm

and the i try this:
1 - I have cleaned the cache $ npm cache clean
2 - sudo npm install -g tishadow, without sudo it not run

but I have the same result:
> tishadow@2.8.1 postinstall /usr/local/lib/node_modules/tishadow
> node cli/tishadow express


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
npm ERR! tishadow@2.8.1 postinstall: `node cli/tishadow express`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the tishadow@2.8.1 postinstall script.
npm ERR! This is most likely a problem with the tishadow package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node cli/tishadow express
npm ERR! You can get their info via:
npm ERR!     npm owner ls tishadow
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 14.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "tishadow"
npm ERR! cwd /Users/giuseppedavidegivitta
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/giuseppedavidegivitta/npm-debug.log
npm ERR! not ok code 0

**Comment by alexgalvagno** [comment]
Hello,
there are no solutions? Any suggestions.

**Comment by nazrdogan** [comment]
do you have teamviewer ? ,I can help you

**Comment by nazrdogan** [comment]
Appcelerator  Studio users need to install  Titanium CLI via npm

<code>
npm  install titanium -g
</code>

David you can close this issue .I solved

**Comment by alexgalvagno** [comment]
Thanks for your time.

**Comment by nazrdogan** [comment]
your welcome
