### ISSUE TITLE
Stops after uploading

### ISSUE THREAD

**Issue by alocin** [dbankier/TiShadow#434]
Hello, I usually launch tishadow as
    `titanium build -p android -T device --shadow`
It's been working quite fine till a few days ago when after modifying the code and saving the compilation stops at "uploading OK" without restarting the app. And if I restart manually the app I can see the changes are not applied.
If I stop tishadow with "ctrl-c" and then restart it I can see the changes.
I'm using version 2.8.1.
Do you have any suggestion?
Thank you!

Nik

**Comment by nazrdogan** [comment]
you can try , tishadow -clear , sometimes  its  stuck.

**Comment by alocin** [comment]
I'll try, thank you Nazir!

**Comment by alocin** [comment]
Working fine and faster! Thanks!
p.s. the correct syntax is 
`tishadow clear` (without "-")

**Comment by nazrdogan** [comment]
your welcome .I remember wrong syntax :)

**Comment by dbankier** [comment]
@nazrdogan thanks for stepping in.
