### ISSUE TITLE
Reference error on update

### ISSUE THREAD

**Issue by shodanuk** [dbankier/TiShadow#436]
I'm currently seeing the following error after making changes to my app. The initial build & deploy works fine. I'm not changing the line or file that this message seems to be referencing and being a part of Alloy, OS_ANDROID is definitely defined. Ctrl-Cing and rebuilding "fixes" the error. 

```
[INFO] [android, 5.0, 192.168.0.5] Requiring: appdata-private://Reflections/android/alloy/controllers/listByTopic.js
[ERROR] [android, 5.0, 192.168.0.5]
Type: ReferenceError
Message: OS_ANDROID is not defined
File: api/PlatformRequire.js
Line: 1
At:   eval at custom_require
```

The command I used to build and deploy is:

    ti build --platform android --target device --device-id 5914be51 --shadow

--appify seems to result in the same behavior.

The device is a Samsung S5 running Android 5.0.

My environment is as follows:

Mac OSX 10.10.3
Node 0.10.38
Ti SDK 4.0.0.v20150512005012
Ti CLI 3.42
TiShadow 2.8.1

**Comment by shodanuk** [comment]
Anyone? Is there any more info I can give that might help debugging?

**Comment by dbankier** [comment]
looks likes like a bad alloy compile. which alloy version?

**Comment by shodanuk** [comment]
It's Alloy 1.7.0-dev. There doesn't appear to be any build issues when not using tishadow. Will try re-installing stable Alloy from NPM and see if it makes a difference.

**Comment by shodanuk** [comment]
Hmm - I'm now not even getting that far. I'm stuck with https://github.com/dbankier/JAST/issues/15 (I'm using JAST, probably should have mentioned that before, sorry!)

**Comment by dbankier** [comment]
OK. Closing here and will follow it up in that repo.
