### ISSUE TITLE
Is there any reason of exclude alloy.js and app.tss when boost watch?

### ISSUE THREAD

**Issue by yomybaby** [dbankier/TiShadow#438]
I use alloy 1.7.0-dev and tishadow 2.8.2.

I like to use `ts @ run -u`(boost).
When alloy.js and app.tss are changed, tishadow shows `[WARN] Nothing to update.`.

I found the reason.
Tishadow excludes `app.js` and `app.tss` from building.

See execute function of `cli/tishadow`:
https://github.com/dbankier/TiShadow/blob/master/cli/tishadow#L209

```javascript
function execute(filename) {
  var argv = process.argv.slice(0);
  if ((argv[2] === "run" || argv[2] === "spec") && filename && !filename.match(/(alloy\.js|app.tss)$/)) {
    argv.push("-f");
    argv.push(filename);
  }
  program.parse(argv);
  // Display help on an invalid command
  if (program.args.length === 0 || typeof program.args[program.args.length -1] === 'string'){
    program.help();
  }
}
```

Is there any reason?

**Comment by dbankier** [comment]
Not sure what might have changed (haven't used alloy for a bit, my current project is Ti classic).
Basically, when implementing the boost way, we couldn't do a paritial compile on those bits due to the global bits in `alloy.js` and/or `app.tss`. Latest alloy might work differently, I'll have a look soon.

**Comment by yomybaby** [comment]
Yes, I'll have a look too.

Additionally, there is another bug with boost.
When saving several files on same time(via. Editor's Save All Menu), only one file affects.
Watching code with gaze should be changed.
Even several files changed, execute be called once with one file.

https://github.com/dbankier/TiShadow/blob/master/cli/tishadow#L231-L239

**Comment by yomybaby** [comment]
When alloy.js modifed, sometimes compiles previous files instead of whole file.
`run` action of command keep property `alloyCompileFile`.
Even there are no `alloyCompileFile`, it keeps last `alloyCompileFile` value.

### Steps to reproduce 
1. run `ts @ run -P iOS -u`
2. modify `index.js` and save (so, alloy compile only index controller)
3. modify `alloy.js` and save (alloy compile also index controller! Yes it's wired)

I don't know what makes this bug. But I can fix that.

See below commit:
https://github.com/yomybaby/TiShadow/commit/72d9eb10846c8a638cf16ae38a77e4456fe8c2c7

**Comment by yomybaby** [comment]
@dbankier Can you have a look this issue? :smile:

**Comment by dbankier** [comment]
Yes.  I will get on to it soon. I am feeling the pain now. 



—

**Comment by yomybaby** [comment]
:+1: Thanks. Everything gonna be alright!

**Comment by dbankier** [comment]
Ok. Worked out the issue. Not in front of a computer at the moment but will have a fix soon. (You will want a full compile still with the app.tss, not sure anymore about alloy.js)



—

**Comment by dbankier** [comment]
I think this does it.

**Comment by yomybaby** [comment]
:+1 Cool! I'll check and let you know that result soon.
2015년 11월 26일 (목) 오후 5:24, David Bankier <notifications@github.com>님이 작성:
