### ISSUE TITLE
Camera view in TiShadow

### ISSUE THREAD

**Issue by m1ga** [dbankier/TiShadow#440]
When I try to open a camera view I'll get the following error:
~~~
Unable to find explicit activity class {com.yydigital.tishadowapp/ti.modules.titanium.media.TiCameraActivity}; have you declared this activity in your AndroidManifest.xml?
~~~
but i don't know how to decalre a custom class in the xml.

**Comment by gimdongwoo** [comment]
Right. this is bug at TiShadow.

So. Added it tiapp.xml

    <android xmlns:android="http://schemas.android.com/apk/res/android">
        <manifest>
            <application>
                        <activity android:name="ti.modules.titanium.media.TiCameraActivity" android:configChanges="keyboardHidden|orientation|screenSize" android:theme="@style/Theme.AppCompat.Translucent.NoTitleBar.Fullscreen"/>
            </application>
            <uses-permission android:name="android.permission.CAMERA"/>
        </manifest>
    </android>

**Comment by dbankier** [comment]
I think I have fixed it now so you won't need the manual addition...

**Comment by yomybaby** [comment]
:+1:

**Comment by gimdongwoo** [comment]
@dbankier Good!! Thank you!!
