### ISSUE TITLE
Builde error using sdk 3.4.1.GA

### ISSUE THREAD

**Issue by cdwlighting** [dbankier/TiShadow#441]
I have an app I am developing, and because of an issue with Tiinpect I have to use 3.4.1.GA.  I can build the app just fine under 3.5.1.GA everything works except I can't set and stop on breakpoints. Well When I switch the SDK from 3.5.1.GA to 3.4.1.GA I get this build error:

[ERROR] Could not find all required Titanium Modules:
[ERROR]    id: yy.tidynamicfont	 version: 0.2.2	 platform: iphone	 deploy-type: development

Nothing has changed except that I downgraded from Titanium SDK 3.5.1 to 3.4.1.  This may be something weird in my environment, but I can't find anything that would help me solve it.  If I run the build without the --shadow switch(at sdk 3.4.1) the build works and I can debug using tiInspector.

Thanks. for the any guidance that might be available.
Chris

**Comment by dbankier** [comment]
That's because >3.5 the native modules needed to be 64-bit compatible - and they are. This means it doesn't work  (and is not found) with 3.4.
Try using an older version of `ts` if you need 3.4. I'd have to dig through the commit logs to find which version was pre-3.5
