### ISSUE TITLE
On Appcelerator Studio seems that TiShadow doesn't work with Alloy projects

### ISSUE THREAD

**Issue by MarioRossi00** [dbankier/TiShadow#445]
Hi, this is my configuration:
0) Win 7 x64
1) Appcelerator Studio 4.0.1
2) Titanium SDK 4.0.0GA
3) Tishadow 2.8.2
4) Node 0.10
5) Tishadow 2.8.2

I cannot use Tishadow on Alloy projects because I get always this error:

[INFO] Beginning Build Process
[INFO] Compiling Alloy for android
"alloy" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
[ERROR] Alloy Compile Error

Of course I can compile projects without problems.
Thanks for attention

**Comment by dbankier** [comment]
Follow this #427
