### ISSUE TITLE
Can't run tishadow express

### ISSUE THREAD

**Issue by tkrz** [dbankier/TiShadow#447]
Since all apps need to be registered in appcelerator, the shadow express build returns message that app is not registered.
Can this be bypassed in some way?

**Comment by dbankier** [comment]
Sorry. I don't use Appcelerator cli - only Titanium cli. Maybe someone else can help.

**Comment by Anatidae-Project** [comment]
Is it possible to build 4.1.0.GA using Titanium CLI instead of appc?

**Comment by dbankier** [comment]
https://github.com/dbankier/tisdk
