### ISSUE TITLE
TiShadow `--shadow` does not work with iOS 9 sims

### ISSUE THREAD

**Issue by skypanther** [dbankier/TiShadow#450]
TiShadow v2.8.2, at least the `--shadow` appified version does not work with Xcode 7 GM, iOS 9 GM, and Ti SDK 5.0.0.RC. Tested in the simulator.

`ti build -p ios --ios-version 9.0 -C <sim_guid> --shadow`

Make changes in the app and save, the console outputs something like the following and then just sits there, the app never reloads:

```shell
...
[INFO] 40 file(s) bundled.
[INFO] Uploading...
OK
```

I have configured an ATS exception in the tiapp.xml as follows. I can access the myinsecuredomain.com site:

```
<key>NSAppTransportSecurity</key>  
<dict>  
    <key>NSExceptionDomains</key>  
    <dict>  
        <key>myinsecuredomain.com</key>  
        <dict>  
            <key>NSExceptionAllowsInsecureHTTPLoads</key>  
            <true/>  
            <key>NSIncludesSubdomains</key>
            <true/>
        </dict>  
        <key>localhost</key>  
        <dict>  
            <key>NSExceptionAllowsInsecureHTTPLoads</key>  
            <true/>  
        </dict>  
        <key>127.0.0.1</key>  
        <dict>  
            <key>NSExceptionAllowsInsecureHTTPLoads</key>  
            <true/>  
        </dict>  
        <key>0.0.0.0</key>  
        <dict>  
            <key>NSExceptionAllowsInsecureHTTPLoads</key>  
            <true/>  
        </dict>  
    </dict>  
</dict>  
```

**Comment by skypanther** [comment]
This issue looks to be the result of https://jira.appcelerator.org/browse/TIMOB-19518

**Comment by dbankier** [comment]
Sorry @skypanther, I haven't installed the iOS9 sims yet. Will soon.

**Comment by skypanther** [comment]
That ticket was the cause of the problem. Using a CI build from 16 September or later or 5.0.0.GA, TiShadow works just fine.

**Comment by dbankier** [comment]
Great.

**Comment by raefa** [comment]
@skypanther Are you sure you did not do anything else? I created a brand new project to test on. I have exactly the same issue you described but I am using 5.0.0.GA. I took the same step of added an ATS exception in the tiapp.xml and I am getting the same thing as you got previously.

TiShadow v2.8.2
Xcode 7 GM
iOS 9 GM
Ti SDK 5.0.0.GA (also tried the latest continuous build for 5.1.0)

**Comment by raefa** [comment]
To add to my previous comment. It is something to do with the simulator. I tried on device (ti build --sdk 5.0.0.GA --platform ios --ios-version 9.0 --target device --shadow) and it works as expected. Odd that it is not working on the simulator but great news for me as I can continue developing with TiShadow!

**Comment by skypanther** [comment]
@raefa Yes, sorry, I'm using more than a simple `ti build` command. Here's the alias from my ~/.bash_profile file that I use for simulator/shadow builds:

```
alias tbis="ti clean && ti build -p ios -C SIMULATOR_GUID --ios-version 9.0 --shadow"
```

Then I can type simply `tbis` to fire up the app in the simulator. I tend to do shadow builds to the device less frequently and don't have an alias created for that case. But, I use a command similar to what you provided in your follow-up comment.

**Comment by raefa** [comment]
@skypanther Thanks but I am also using the same command too. Still no go. Hmmm. Very odd that it works on device but not the simulator. If you have any other ideas I'm all ears! :)

**Comment by raefa** [comment]
As discussed in this issue (https://github.com/dbankier/TiShadow/issues/458#issuecomment-145646303), putting `-o 127.0.0.1` in the command got TiShadow working for me on the simulator.

```
ti build --sdk 5.0.2.GA --skip-js-minify --platform ios --ios-version 9.0 --target simulator --device-id ? -o 127.0.0.1 --shadow
```
