### ISSUE TITLE
TiShadow in the future?

### ISSUE THREAD

**Issue by bitfabrikken** [dbankier/TiShadow#451]
Now that LiveView is integrated in Appcelerator Studio, will TiShadow still be developed on? 
I very much prefer TiShadow, so I really hope the answer is yes :)

Apologies if this is not the correct place to post this - but don't know where else to post it (if not correct place, kindly point me to it).

**Comment by caspahouzer** [comment]
I really hope it, too. LiveView is nice, but using it with Appcelerator Studio is a real hell of memory lagging

- Sebastian

**Comment by bitfabrikken** [comment]
Also LiveView is extremely slow IMO, and seems more like an alpha release rather than TiShadow that's like a solid, stable release.

**Comment by iotashan** [comment]
LiveView is also not OSS, and requires a paid account.

**Comment by dbankier** [comment]
Yes the plan is to continue TiShadow development. For the record - TiShadow pre-dated LiveView. I presented it at CodeStrong, Appcelerator gave me an award for it... then copied it. Currently I am only using the free and open source Titanium stack so I have an interest in ensuring it continues to work.

The reason I haven't been working on the issues lately is I have been quite busy on some large projects. They are mostly backend (node) ones which is also why the more recent issues haven't really bothered me in my day-to-day work.

I had ambitious plans for TiShadow (see #340) but with all the new native js frameworks and a bit of FUD about Appcelerator it has given me pause for thought before really spending that much time in overhauling TiShadow. To be absolutely clear, Titanium is still far superior to anything out there.

Hope that clear things up. Hope to get back to ts soon.
