### ISSUE TITLE
DefaultIcon ignored

### ISSUE THREAD

**Issue by caspahouzer** [dbankier/TiShadow#453]
Hello,

with 5.0.0 come the automated image assets generation. TiShadow says, I have to put the DefaultIcon.png with 1024x1024 in the root folder. I did so, but the error message says, that the file is missing.

Where exactly do I have to put it in?

**Comment by raefa** [comment]
I had this issue too. The error message also said something about the DefaultIcon.png being used to create missing icon images at various sizes. If you manually create the icons for the different sizes and place them in the relevant directories this error goes away. The files I had to add were:

/app/assets/iphone/appicon-76.png
/app/assets/iphone/appicon-76@2x.png
/app/assets/iphone/appicon-Small-40.png
/app/assets/iphone/appicon-Small-40@2x.png

**Comment by dbankier** [comment]
fixed

**Comment by caspahouzer** [comment]
How to update? Is it npm available yet?

**Comment by dbankier** [comment]
Haven't pushed a new version yet. A few more things I'd like to clean up from 5.0.0.
If you want to install from master using this command: `npm install -g dbankier/TiShadow`
