### ISSUE TITLE
iOS: Same simulator started every time

### ISSUE THREAD

**Issue by caspahouzer** [dbankier/TiShadow#454]
When I < 5.0.0 executed

~~~
ti build -p ios -T simulator --shadow -Y ipad
~~~

the ipad started. now I have to enter the complete device id to start the correct simulator

**Comment by dbankier** [comment]
Doesn't look like a tishadow thing. You get the same issue without the `--shadow` flag.

**Comment by caspahouzer** [comment]
ok, didn’t try that. Sorry

- Sebastian

**Comment by dbankier** [comment]
no problem

**Comment by caspahouzer** [comment]
Everybody who's interested: https://jira.appcelerator.org/browse/AC-370
