### ISSUE TITLE
Get App Transport Security error when trying to connect to tiShadow Server.

### ISSUE THREAD

**Issue by kgividen** [dbankier/TiShadow#455]
I get the following error from the TiShadow app on iOS when trying to connect to the tiShadow Server.  

"Alert Connect Failed.  The resource could not be loaded because the App Transport Security policy requires the use of a secure connection."

This used to work but I recently updated XCODE and iOS9 so maybe that broke something?

**Comment by kgividen** [comment]
It looks like this is in fact an iOS9 thing.  
https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/index.html

I tried adding the below to the tiapp.xml but it doesn't seem to work even though the Info.plist seems to have it.  Not sure why that wouldn't work...

  <ios>
    <plist>
      <dict>
        <key>NSAppTransportSecurity</key>
          <dict>
            <key>NSAllowsArbitraryLoads</key><true/>
          </dict>
      </dict>
    </plist>
  </ios>

**Comment by dbankier** [comment]
Hmm... which TiSDK are you using? Not having an issues myself.

**Comment by kgividen** [comment]
I'm using 4.1.0.GA.  It looks like Appcelerator disables this by default in 5.0.0
http://docs.appcelerator.com/platform/release-notes/?version=5.0.0.Beta

So I'm going to try that now and see if it works.

**Comment by kgividen** [comment]
Yea...as expected upgrading to 5.0 works.  However, the app is missing the DefaultIcon.png in the root and since there are new dependency on icons it fails to build.  I put a temporary icon in there and things seem to be loading now.

**Comment by dbankier** [comment]
The default icon issue is fixed in master.



—

**Comment by kgividen** [comment]
I installed via 'npm install -g dbankier/TiShadow' and it didn't seem to be fixed.  But I haven't troubleshot that at all since I just shoved a temp icon in there.

**Comment by caspahouzer** [comment]
@kgividen I also installed via  'npm install -g dbankier/TiShadow' and can confirm the DefaultIcon problem as fixed
