### ISSUE TITLE
New OSX, El Capitan troubles

### ISSUE THREAD

**Issue by tujoworker** [dbankier/TiShadow#458]
Hi David,

thanks for making TiShadow that great!
Few days ago i converted my whole workflow from Appcelerator/Titanium Studio to Atom and TiShadow. Today, El Capitan, the new OSX was released and I downloaded and installed it. But then:

* I run $ "ti build" or $ "appc run" with --appify or --shadow and $ "ts @ run -u" 

* No Devices are visible in the list: http://localhost:3000/

* Live Editing/Updating is not working.

For now, I download xcode 7.0.1, maybe this can help. I'l update tests after that.
Someone else had same issue?

**Comment by caspahouzer** [comment]
I decided today switching to El Capitan. But with this issue, I will think about it again

**Comment by tujoworker** [comment]
No, xcode 7.0.1 did not help.
Once I change/edit files I see the changes in the Terminal CLI like this:

[DEBUG] changed: /Applications/XAMPP/xamppfiles/htdocs/.../Titanium/Resources/File.js
[INFO] Beginning Build Process
[INFO] 1 file(s) bundled.
[INFO] Uploading...
.write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.

**Comment by caspahouzer** [comment]
I think, this is a very heavy issue and should be solved quick!

**Comment by raefa** [comment]
@tujoworker and @caspahouzer This issue sounds much like the issue I commented on here:
https://github.com/dbankier/TiShadow/issues/450

I am seeing no Devices visible in the list on http://localhost:3000/ (which I actually did not check previously). For me, Live Editing/Updating is not working on the simulator only. It is working on devices. If this is causing you grief as a temporary measure hopefully you too can get it working on a device.

**Comment by maximilianmessing** [comment]
I have the same issue...

**Comment by tujoworker** [comment]
LiveView by Appcelerator Studio has as well troubles with El Capitan.
So maybe TiShadow do have kind of the same issue (host IP)?

Se JIRA ticket: https://jira.appcelerator.org/browse/TISTUD-7747

**Comment by maximilianmessing** [comment]
choosing 127.0.0.1 as the host ip worked out for me...

**Comment by tujoworker** [comment]
@maximilianmessing Where do you make this changes for TiShadow?

**Comment by maximilianmessing** [comment]
I tried tishadow config -o 127.0.0.1 and tested against the local simulator (--appify). this won't work out for deploys on real devices though

**Comment by yomybaby** [comment]
I have a same issue.

As @maximilianmessing  mentioned, after setting `tishadow config -o localhost`, it works on simulator only.  I think that it related to `NSAppTransportSecurity` (#450). 
But even allow ArbitraryLoads , it doesn't work. (see below code)

```
<ti:app>
  ...
  <ios>
    <plist>  
      <dict>
        <key>NSAppTransportSecurity</key>  
        <dict>
          <key>NSAllowsArbitraryLoads</key><true/>
        </dict>
      </dict>  
    </plist>  
  </ios>
  ...
</ti:app>
```

### The only clue that I found
When appify app try to connect to server right after launching, app send GET `http://192.168.0.222:3000/socket.io/1/?t=Tue%20Oct%2006%202015%2005%3A02%3A10%20GMT%2B0900%20%28KST%29` request repeatedly.

**Comment by caspahouzer** [comment]
https://github.com/dbankier/TiShadow/issues/450#issuecomment-145662455

solved it for me on simulator

**Comment by dbankier** [comment]
I have been away. I'm upgrading now so I'll be working on it.

**Comment by yomybaby** [comment]
Great news!!
2015년 10월 6일 (화) 오후 8:08, David Bankier <notifications@github.com>님이 작성:

**Comment by caspahouzer** [comment]
Thanks!

**Comment by levani** [comment]
I have the same problem after updating to El Capitan. The app is re-building when I save changes but the simulator doesn't update.

**Comment by tujoworker** [comment]
Nice @dbankier! I bet this issue is not effected in iOS8 simulator/device, but only iOS9 - we talk probably about an IPv6 issue by NSURLSession. Se the news here https://developer.apple.com/news/?id=08282015a and a ton of issues/comments: https://forums.developer.apple.com/thread/13472

Does TiShadow use Ti.Network.HTTPClient for communication? Then probably there we have the problem.

**Comment by dbankier** [comment]
Ok. It looks like a routing issue (*not* NSURLSession related) in the simulators and not app or tishadow specific.
The simulator is given the ip-address of your machine which tishadow is using (confirmed using the `Ti.Platform.*` APIs).
To prove the point you can try and connect to the tishadow web interface from safari in the simulator -  using the ip-address of the simulator/machine won't work, but the 127.0.0.1 address does.

Everything works on the device as is so you don't need to panic.

For the moment, use the `-o 127.0.0.1`  flag as pointed out above if you want to use the simulator.

I'll add a fix soon that will detect if you are using the simulator and connect to `127.0.0.1` instead of the configured ip-address automatically.
It is a really simple fix / work around.

**Comment by dbankier** [comment]
done

**Comment by dbankier** [comment]
pushed a new version to npm v2.8.3

**Comment by yomybaby** [comment]
Everything works on the device as is ??

What Version of iOS which installed your test iOS device?

My iphone(iOS 9.0.2) doesn't work properly with tishadow as I mentioned
before.

2015년 10월 7일 (수) 오후 4:17, David Bankier <notifications@github.com>님이 작성:

**Comment by dbankier** [comment]
@yomybaby, ti 5.0.2.GA, ipad air, ios 9.0.2. 
Clean build and uninstalled the old app that was there.

**Comment by yomybaby** [comment]
It works. :+1: Thanks.
I don't know why it didn't work few days ago. But today, it work!

Sorry for confusing.
