### ISSUE TITLE
REPL is truncating chars

### ISSUE THREAD

**Issue by kopiro** [dbankier/TiShadow#461]
I know that seems unreasonable, but the REPL is truncating charaters ([0] and [end]).

![image](https://cloud.githubusercontent.com/assets/839700/10310431/3f70d0e4-6c42-11e5-846f-1448b9a26f8e.png)

**Comment by dbankier** [comment]
hmmm... platform? version?

**Comment by kopiro** [comment]
Tried on 2 different Macs:
- tishadow 2.8.2 and master branch
- OSX 10.10 / 10.11

**Comment by dbankier** [comment]
what node version?

**Comment by kopiro** [comment]
v0.12.7

**Comment by yomybaby** [comment]
same here.
I use node v0.12.7, too.

**Comment by dbankier** [comment]
repl behaves differently >0.10. Fixed now.

**Comment by kopiro** [comment]
Thanks!
