### ISSUE TITLE
Update getting started page

### ISSUE THREAD

**Issue by bitfabrikken** [dbankier/TiShadow#462]
http://tishadow.yydigital.com/getting%20started/

Says to use "titanium build -p android -T device"
Should be "appc ti build -p android -T device"

I think... ? :)

**Comment by bitfabrikken** [comment]
Running with the recommended command gives:
[ERROR] Failed to encrypt JavaScript files
[ERROR] This application cannot be built with the Titanium open source SDK because it is an Appcelerator Platform registered application. Please use the Appcelerator Platform CLI tools or Appcelerator Studio to build this application.

**Comment by shodanuk** [comment]
Actually, that depends on whether you’re using the open source Titanium CLI + SDK or using the appcelerator (appc) command. It's perfectly possible to build a Titanium app without ever touching the appc command.
On 6 November 2015 at 13:56:52, Dan Kronholm, Bitfabrikken (notifications@github.com) wrote:

http://tishadow.yydigital.com/getting%20started/

Says to use "titanium build -p android -T device"
Should be "appc ti build -p android -T device"

**Comment by bitfabrikken** [comment]
How would I go about doing that, so the recommended build command works?

**Comment by shodanuk** [comment]
I believe it's down to how you generated the project in the first place. If you use `ti create` from the command line then I believe that creates an open source Ti project. If you created it using `appc` or Appcelerator Studio, I think it's an "appc" project by default. In practice, I think the only difference is a <property> element in your tiapp.xml containing an appc-app-id. I suspect if you remove that line and try again, the `ti build` might work.

Of course, you'll lose any "benefits" of it being a Appcelerator Platform app, like analytics etc.

Also, if you create an open source project using `ti create` and then import that into Studio, it'll convert it to an Appcelerator Platform app.

**Comment by bitfabrikken** [comment]
Thank you kindly, I definitely don't want it to be an appc app right now.
