### ISSUE TITLE
TiShadow App crashes after connecting to server

### ISSUE THREAD

**Issue by buttonfreak** [dbankier/TiShadow#463]
I'm having some issues with 2.8.3 and TI SDK 5+ . I've tried on Genymotion on a API22 android device, on a Sony Z3 compact Tablet  with 5.1.1 and a HTC M8 with 5.1.1. After deploying the TIShadow app to one of those devices and pressing connect the app crashes immediately without any form of error-messages.. It seems it does connect to the TIShadow server, after which it crashes. Haven't tried iOS.

**Comment by yomybaby** [comment]
I have a similar problem. It's crashes right after launching on API22 devices with TiSDK 5+.
I try to find a reason.
In my opinion, `ti.compression` module make this problem. 

If I remove `ti.compression` module of `build/appify/tiapp.xml`, app didn't crash.
I'm not sure but we should find a alternative module for android unzipping.

**Comment by yomybaby** [comment]
If you use genymotion, you have to install google api to your genymotion image.

**Comment by dbankier** [comment]
merged yomybaby's commit - closing - thanks.
