### ISSUE TITLE
App not updated on OSX

### ISSUE THREAD

**Issue by alocin** [dbankier/TiShadow#465]
Hi David,
I've installed tishadow 2.8.3 on OSX Yosemite and I'm using Accelerator Studio 4.3.3
I run the command 
`appc run -p android -T device --shadow` inside the app directory and the app starts correctly on the Android device. But when I make a change inside studio and save it, the app is not updated and in the shell where I launched the command nothing appens, while it gets correctly updated when I interact with the app.
What can I do?

Thank you.
Nik

**Comment by dbankier** [comment]
if you are using the appcelerator cli and not titanium use the following command first:

~~~
ts config --use-appc-CLI
~~~
