### ISSUE TITLE
Testing with TiShadow express?

### ISSUE THREAD

**Issue by aaronksaunders** [dbankier/TiShadow#475]
Is it possible to run specs using tiShadow express?

**Comment by dbankier** [comment]
Hi @aaronksaunders,

Yes it should work. You can use the example in the repo as a guide.

I just did the following:

~~~
$ ti build -p ios --shadow
~~~

then in a different terminal window

~~~
$ ts spec
~~~

you can use the following if you want to run specs on changes

~~~
$ ts @ spec
~~~

The results of the test will appear in the first terminal window.

**Comment by aaronksaunders** [comment]
I was trying to do it al in one command, thabjs
