### ISSUE TITLE
Can't install TiShadow

### ISSUE THREAD

**Issue by developer82** [dbankier/TiShadow#476]
I've tried both `$ npm install -g tishadow` and `sudo npm install -g tishadow --unsafe-perm`

This is the error I'm getting:

npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated has-color@0.1.7: Renamed to supports-color. If you're using chalk, upgrade to the latest version. https://github.com/chalk/supports-color
/usr/local/bin/tishadow -> /usr/local/lib/node_modules/tishadow/cli/tishadow
/usr/local/bin/ts -> /usr/local/lib/node_modules/tishadow/cli/tishadow

> ws@0.4.32 install /usr/local/lib/node_modules/tishadow/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o

> tishadow@2.8.5 postinstall /usr/local/lib/node_modules/tishadow
> node cli/tishadow express

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn ti ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickDomainCallback (node.js:429:17)
    at Function.Module.runMain (module.js:431:11)
    at startup (node.js:139:18)
    at node.js:999:3
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "tishadow" "--unsafe-perm"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! tishadow@2.8.5 postinstall: `node cli/tishadow express`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tishadow@2.8.5 postinstall script 'node cli/tishadow express'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tishadow package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node cli/tishadow express
npm ERR! You can get their info via:
npm ERR!     npm owner ls tishadow
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ophir/npm-debug.log

How can I install?

**Comment by m1ga** [comment]
Could you try and install node 4.2.2 (e.g. using `npm install -g  n && n 4.2.2`)? Newer versions are not supported by Appcelerator (https://wiki.appcelerator.org/display/guides2/Installing+Node) and I'm not sure what the max version of tishadow is.
With 4.2.2 its working for me and npm 2.14.7. I'm getting the lodash warning too (from gaze) but its still installing

**Comment by dbankier** [comment]
which cli are you running `ti` or `appc`?

**Comment by rygh4775** [comment]
I got same problem below as well..

npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0

> ws@0.4.32 install /usr/local/lib/node_modules/tishadow/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> ws@0.4.32 install /usr/local/lib/node_modules/tishadow/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
/usr/local/bin/tishadow -> /usr/local/lib/node_modules/tishadow/cli/tishadow
/usr/local/bin/ts -> /usr/local/lib/node_modules/tishadow/cli/tishadow

> tishadow@2.8.5 postinstall /usr/local/lib/node_modules/tishadow
> node cli/tishadow express

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn ti ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickDomainCallback (node.js:381:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
24012 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/tishadow/node_modules/express/node_modules/connect/node_modules/serve-static/node_modules/send/node_modules/statuses
24013 silly gentlyRm /usr/local/lib/node_modules/tishadow/node_modules/express/node_modules/connect/node_modules/serve-static/node_modules/send/node_modules/depd is being purged from base /usr/local
24014 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/tishadow/node_modules/express/node_modules/connect/node_modules/serve-static/node_modules/send/node_modules/depd
24015 silly gentlyRm /usr/local/lib/node_modules/tishadow/node_modules/express/node_modules/connect/node_modules/serve-static/node_modules/send/node_modules/destroy is being purged from base /usr/local
24016 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/tishadow/node_modules/express/node_modules/connect/node_modules/serve-static/node_modules/send/node_modules/destroy
24017 verbose unbuild lib/node_modules/tishadow/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/raw-body
24018 verbose unbuild lib/node_modules/tishadow/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/on-finished
24019 verbose unbuild lib/node_modules/tishadow/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/iconv-lite
24020 info linkStuff path-is-absolute@1.0.0
@                                                                               @
"~/npm-debug.log" [readonly] 16216L, 1276192C
    at node.js:814:3
npm ERR! Darwin 15.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "tishadow" "--unsafe-perm"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! tishadow@2.8.5 postinstall: `node cli/tishadow express`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tishadow@2.8.5 postinstall script 'node cli/tishadow express'.
npm ERR! This is most likely a problem with the tishadow package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node cli/tishadow express
npm ERR! You can get their info via:
npm ERR!     npm owner ls tishadow
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cho/npm-debug.log

**Comment by rygh4775** [comment]
I have experienced same problem and I solved that.
Even though I installed Titanium studio. Titanium CLI was not searched properly.
So, you can try below to install Titanium CLI.

> # sudo npm install titanium -g

**Comment by adampax** [comment]
Same error on a new machine where everything was installed with the Appcelerator Studio wizard, and installing titanium module manually per @rygh4775 fixed it for me.  

Apparently Studio doesn't bother installing the titanium module! :frowning:

**Comment by dbankier** [comment]
They hide it under the `appc` cli command, so if you aren't using the open source route you need to use `appc ti` instead of `ti`. I think fokke has a module that does a smart switch to discover which command to use (appc or ti), but I'm currently only using the open source way so I can't use/test against it.

**Comment by drunnells** [comment]
I ran into the same problem with a fresh install of Appcelerator Studio 4.5 on my Mac. I'm sure this isn't the best way, but I was able to get tishadow installed after creating a script named /usr/local/bin/ti that just calls appc ti. I also symlinked /usr/local/bin/titanium to it:

```
#!/bin/sh
appc ti "$@"
```

**Comment by anik786** [comment]
I had the same problem. The problem is that tishadow is using the free version of titanium (i.e. `ti` instead of the paid version `appc ti`. A simple solution is to install the free version as well like so:
```
sudo npm install titanium -g
```

You can then install tishadow normally like so:
```
sudo npm install -g tishadow --unsafe-perm
```

You can then tell tishadow to use the paid version of Titanium like so:
```
ts config --use-appc-CLI
```

In order to prevent issues like this happening to other people can we please:
 1) Update the README file to tell them to install the normal version of Titanium
 2) Fix TiShadow so that if `ti` is not available, it uses `appc ti`. Alternatively, just ask the user which one it should use.
