### ISSUE TITLE
endless loop with alloy 1.8.3

### ISSUE THREAD

**Issue by TheFortunate75** [dbankier/TiShadow#481]
When calling `ti build -p ios -T simulator --shadow` there seems to be an endless loop.
The simulator will not start.
I guess it is resulting from the now generated folders  i18n and platform (since alloy 1.8).
I am using titanium 5.0.6, alloy 1.8.3 and tishadow 2.8.5.

**Comment by furthurr** [comment]
I have the same issue :( ...

**Comment by renekiel** [comment]
I can confirm this issue. Looking forward for yomybaby's fix
