### ISSUE TITLE
Can't install master version directly from github

### ISSUE THREAD

**Issue by albinotonnina** [dbankier/TiShadow#487]
`npm install -g dbankier/TiShadow` 
the procedure gets stuck

**Comment by dbankier** [comment]
I'll need more details.

**Comment by albinotonnina** [comment]
`npm info it worked if it ends with ok
npm verb cli [ '/usr/local/Cellar/node/5.2.0/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '-g',
npm verb cli   'dbankier/TiShadow',
npm verb cli   '--verbose' ]
npm info using npm@3.3.12
npm info using node@v5.2.0
npm verb cache add spec dbankier/TiShadow
npm verb addRemoteGit caching dbankier/TiShadow
npm verb addRemoteGit dbankier/TiShadow is a repository hosted by github
npm verb tryClone git-github-com-dbankier-TiShadow-git-0522325847a85e632250e077516896ce not in flight; caching
npm info git [ 'clone',
npm info git   '--template=/Users/me/.npm/_git-remotes/_templates',
npm info git   '--mirror',
npm info git   'git://github.com/dbankier/TiShadow.git',
npm info git   '/Users/me/.npm/_git-remotes/git-github-com-dbankier-TiShadow-git-0522325847a85e632250e077516896ce' ]`


then well, nothing!
Did it help?

**Comment by dbankier** [comment]
Master takes a long time to clone.

**Comment by albinotonnina** [comment]
humbly sorry then 👍

**Comment by dbankier** [comment]
Instead next time try manually cloning using `--depth 1` and then `npm link`
