### ISSUE TITLE
tishadow appify [ERROR] You really don't want to write to the current directory.

### ISSUE THREAD

**Issue by ikalangita** [dbankier/TiShadow#488]
Hello,
Here i how install and use tishadow 

*_Install and make a tishadow project
*_`sudo npm -g tishadow`
`mkdir ~/tishadowapp && tishadow app -d ~/tishadowapp`
*_Running the server
*_`tishadow server`

**Now let's run it**
`tishadow run` 
**This appears and no simulator opened, normal ?**
`sh-3.2# tishadow run
[INFO] Beginning Build Process
[INFO] 59 file(s) bundled.`

*_Now i go to my titanium folder project
*_`tishadow appify`

and this error showing 

`[INFO] Beginning Build Process
[INFO] Compiling Alloy for android
[WARN] Generated "/i18n" directory is not ignored by Git, please add it to your .gitignore
[WARN] Generated "/platform" directory is not ignored by Git, please add it to your .gitignore
[INFO]  [config.json] regenerating CFG.js from config.json...
[INFO] ----- MVC GENERATION -----
[INFO] [app.tss] global style processing...
[INFO] [global style] writing to cache...
[INFO] [index.xml] view processing...
[INFO]   style:      "index.tss"
[INFO]   view:       "index.xml"
[INFO]   controller: "index.js"
[INFO]   created:    "Resources/android/alloy/controllers/index.js"
[INFO]   created:     "Resources/android/alloy/styles/index.js"
[INFO] 
[INFO] [app.js] Titanium entry point processing...
[INFO]   created:    "Resources/android/app.js"
[INFO] 
[INFO] ----- OPTIMIZING -----
[INFO] - android/alloy.js
[INFO] - android/alloy/sync/localStorage.js
[INFO] - android/alloy/sync/properties.js
[INFO] - android/alloy/sync/sql.js
[INFO] 
[INFO] Alloy compiled in 1.17949s
[INFO] Compiling Alloy for ios
[WARN] Generated "/i18n" directory is not ignored by Git, please add it to your .gitignore
[WARN] Generated "/platform" directory is not ignored by Git, please add it to your .gitignore
[INFO]  [config.json] config.json unchanged, using cached config.json...
[INFO] ----- MVC GENERATION -----
[INFO] [global style] loading from cache...
[INFO] [index.xml] view processing...
[INFO]   style:      "index.tss"
[INFO]   view:       "index.xml"
[INFO]   controller: "index.js"
[INFO]   created:    "Resources/iphone/alloy/controllers/index.js"
[INFO]   created:     "Resources/iphone/alloy/styles/index.js"
[INFO] 
[INFO] [app.js] Titanium entry point processing...
[INFO]   created:    "Resources/iphone/app.js"
[INFO] 
[INFO] ----- OPTIMIZING -----
[INFO] - iphone/alloy.js
[INFO] - iphone/alloy/sync/localStorage.js
[INFO] - iphone/alloy/sync/properties.js
[INFO] - iphone/alloy/sync/sql.js
[INFO] 
[INFO] Alloy compiled in 1.23598s
[INFO] 51 file(s) bundled.
[INFO] Bundle Ready: /Users/esy/Documents/Appcelerator_Studio_Workspace/composants/build/tishadow/dist/composants.zip
**[ERROR] You really don't want to write to the current directory**.`

Thanks for your help

**Comment by yomybaby** [comment]
If you want to run very easy way, just use `ti build -p ios --shadow`.

The steps which I use :
1. `ts server -z` : 
2.`ts @ run -u` : watch & auto run
3. `ti build -p ios --appify` / `ti build -p android --appify`

More detail in https://github.com/dbankier/TiShadow/blob/master/README.md

**Comment by ikalangita** [comment]
Hello,
thank you for reply, all those commands should be run on titanium folder?

**Comment by yomybaby** [comment]
The command of step 2 and 3  should be run on root of Ti project folder.
`ts server ` can be run anywhere.

**Comment by ikalangita** [comment]
I'll try that thank you

**Comment by ikalangita** [comment]
Hello when doing the appify last command `ti build -p ios --appify` i got this :
`Error: Cannot find module '/Users/xxx/Library/Application Support/Titanium/mobilesdk/osx/5.0.1.GA/node_modules/sqlite3/lib/binding/node-v46-darwin-x64/node_sqlite3.node'`
