### ISSUE TITLE
TiShadow iOS App disconnects on every bundle unpacking

### ISSUE THREAD

**Issue by ulizama** [dbankier/TiShadow#490]
I downloaded the TiShadow iOS App, I'm able to connect to my TiShadow server correctly, but everytime I send a:
`tishadow run`
or
`tishadow run --update`

The app disconnects when it unpacks the content:
```
DEBUG] A socket connected
[INFO] [CONTROLLER] Connected
[INFO] New Bundle: /Users/ulizama/Documents/Apps/DesignerApp/build/tishadow/dist/Designer.zip | Designer
[DEBUG] Bundle requested.
[INFO] [iphone, 9.3.1, 192.168.1.68] Unpacking new bundle: Designer
[WARN] [iphone, 9.3.1, 192.168.1.68] Disconnected
```

I have to restart the app and when it launches the updated contents are there.

I have the latest TiShadow version installed directly from the repo:
```
tishadow -v
2.8.6
````

**Comment by dbankier** [comment]
Arghh! Looks like `Ti.App._restart()` isn't available in the app store build.
It is meant to disconnect and reconnect after the restart.

Working on a fix now.

**Comment by dbankier** [comment]
This: https://github.com/appcelerator/titanium_mobile/blob/master/iphone/Classes/AppModule.m#L35

**Comment by dbankier** [comment]
Submitting update now.

**Comment by dbankier** [comment]
Ok. Update went through, but it looks like I need to remove these two as well:

https://github.com/appcelerator/titanium_mobile/blob/415bd6c66dcc55b1a59a59574f3babd3c3a84ede/iphone/Classes/TiRootViewController.h#L69
https://github.com/appcelerator/titanium_mobile/blob/415bd6c66dcc55b1a59a59574f3babd3c3a84ede/iphone/Classes/TiRootViewController.m#L756

Can anyone see anything else I'm missing...

**Comment by dbankier** [comment]
Found one more, resubmitting...
Sorry for this. Fortunately the App Store turnaround time is faster these days...

**Comment by dbankier** [comment]
Verified with adhoc build. This one should be good.

**Comment by acaland** [comment]
Did you update to 5.2.2.GA too?

**Comment by jasonkneen** [comment]
This is working better for me -- but still getting an issue when trying to do a file chance and using @ run --update, the device goes blank and disconnects

**Comment by dbankier** [comment]
@jasonkneen.  Yep. That's what the next update which I sent to app store this morning is about.
This comment: https://github.com/dbankier/TiShadow/issues/490#issuecomment-220206258 explains it. 
I hadn't expected appc to pull out all the _restart stuff from the production build (which they hadn't when I tried in the past). There were a few places I need to hack. The next update should work.

**Comment by jasonkneen** [comment]
Got it -- thanks

**Comment by dbankier** [comment]
Ok. We are up and running.
The latest update is released and  works. It is running 5.2.2.GA.
Have fun playing, educating, etc. 
Be sure to tries those things that you might haven't yet (if you have just been using express mode). Repl, pipe2repl, spies, screenshots, webpage, tests, etc...
