### ISSUE TITLE
ti build fails when using --shadow

### ISSUE THREAD

**Issue by justingreerbbi** [dbankier/TiShadow#494]
When adding `--shadow` to the build command the compiler will fail with the follwoing error.

`/Debug-iphoneos/Positive\ Peers.build/Objects-normal/armv7/TiUIiOSProxy.o Classes/TiUIiOSProxy.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[ERROR] (1 failure)
`

Replicate Steps:
1. Running Command `ti build -T device -p iphone` (Project will build correctly)
2. Run command `ti build -T device -p iphone --shadow` 

Step 2 will cause build to fail.

**Tested On**
CLI: 5.0.5
SDK Version 6.0.0.v20160615112826 & 5.4.0.v20160224050025
TiShadow 2.8.6

**Comment by dbankier** [comment]
I haven't installed non-GA builds, so I can't test at the moment.

**Comment by Astrovic** [comment]
I've the same issue with Ti SDK 6 RC

**Comment by dbankier** [comment]
Testing now with GA and the latest ts and I can't replicate. You still having issues?

**Comment by Astrovic** [comment]
The issue persists if you build it on the device:
`appc ti build -p iphone -t device --shadow`

**Comment by dbankier** [comment]
hmmm... worked for me. Can you please try the latest version of ts (pushed to npm about an hour ago).

**Comment by Astrovic** [comment]
Sorry, you're right, now it works!
I tried with the pull of @gimdongwoo, but it had not yet been updated the `..api/Includes.js` with the new iOS API. Now it works perfectly, great job! 👍 👍 👍

**Comment by dbankier** [comment]
Thank you.
