### ISSUE TITLE
Ti.App.Properties

### ISSUE THREAD

**Issue by kopiro** [dbankier/TiShadow#495]
Hi!

I saw in the code that in `api/TiShadow/clearCache` you delete all Ti.App.Properties that DOESN't match `^tishadow:`.

Is it correct? We store important data in the TiAppProperties that we won't lose after a full rebuild.

**Comment by dbankier** [comment]
Yes. It is correct. `clearCache` is effectively like uninstalling the (cached) app.

**Comment by kopiro** [comment]
Ok, but you do on startup every-time, deleting stored properties :(

**Comment by dbankier** [comment]
It doesn't `clearCache` every time either, only on new appify or when requested.

**Comment by kopiro** [comment]
But, using `--shadow` is a new appify?

**Comment by caspahouzer** [comment]
same problem here and still no answer :-(
