### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by kopiro** [dbankier/TiShadow#499]
Tishadow: 2.8.7
Alloy: 1.9.2
SDK: 5.5.0.GA

Infinite loop.

**Comment by dbankier** [comment]
I need more details please.

**Comment by kopiro** [comment]
It starts compiling alloy, after starts the Titanium SDK complilation.
After that, alloy compile again and an infinite loop from tishadow and alloy starts.

Do you want the entire log?

**Comment by dbankier** [comment]
Are you using express mode? Probably an issue with the "watch" filter.
Will look at it tomorrow...

**Comment by dbankier** [comment]
fixed with this: https://github.com/dbankier/TiShadow/commit/51323ca90b15f7e1bcfd0eaafa725fda696ff9fd

some chokidar issue... I'm working around it for the moment, but the loop has stopped.

2.8.8 is on its way to npm.

**Comment by kopiro** [comment]
Solved, thank you!
