### ISSUE TITLE
Securely issue

### ISSUE THREAD

**Issue by markruys** [dbankier/TiShadow#503]
Related to [iOS 10 needs keychain entitlements](https://github.com/benbahrenburg/Securely/issues/48), I have the problem that bencoding.securely works fine with Ti SDK 5.5.0, but when I run with TiShadow 2.8.8 enabled. It seems to me that our custom myApp.entitlements is not picked up by TiShadow. In [How to use Ti.Facebook in TiShadow](http://fokkezb.nl/2013/04/18/how-to-use-ti-facebook-in-tishadow/), Fokke explains that he needed to modify TiShadow App's tiapp.xml, but I can't find out how he did it. Any help/tips appreciated.

**Comment by dbankier** [comment]
this is solved with a recent PR. I need to push a new version to npm.
