### ISSUE TITLE
When boost is on, changes will not be deployed.

### ISSUE THREAD

**Issue by gimdongwoo** [dbankier/TiShadow#504]
Ti SDK 5.5.0.GA & 5.5.1.GA
Alloy 1.9.2
Tishadow 2.8.8 (2.8.7 had same problem)
Node 5.11.1

When boost is on, changes will not be deployed.

I't seems that is normally distributed, but changes will not be deployed.

./build/tishadow
./Resources
Code is not changed.

Tishadow 2.8.6 is ok.

Maybe I think this related this commit.
https://github.com/dbankier/TiShadow/commit/520ed534fda058855465bb7dd13692c3a19620bb

**Comment by dbankier** [comment]
Noticed that too. Looking into it.

**Comment by gimdongwoo** [comment]
@dbankier Thank you!!

I love tishadow. And, I respect you deeply.

I knew today, you're living in Melbourne!
My old friend living in Melbourne, I would like to go to Melbourne.
