### ISSUE TITLE
error when build 

### ISSUE THREAD

**Issue by ikalangita** [dbankier/TiShadow#506]
Hello,

Someone know why i get error : Invalid Titanium project path (no tiapp.xml) when build with sublime text ? this is my config 
    {
        "cmd": ["tishadow run -P ios -u"],
        "shell": "bash",
        "path": "/usr/local/bin/",
       "working_dir": "$project_path"
    }
Thanks folks

**Comment by dbankier** [comment]
Not sure about sublime, but tiapp.xml must be in your cwd.
