### ISSUE TITLE
Deploy via "Code push"

### ISSUE THREAD

**Issue by yomybaby** [dbankier/TiShadow#515]
This issue is an suggestion.

How about using code push for titanium?
https://microsoft.github.io/code-push/

Is there anyone already tried?

**Comment by dbankier** [comment]
I built something like this a few years ago but with more (remember ticaster). I add things like A-B testing, etc. Didn't get much interest though...

**Comment by yomybaby** [comment]
@dbankier I remember ticaster. :) Already you know Apple didn't allow this mechanism before. But now they allows.
You made several awesome software before Facebook and MS. 👍
