### ISSUE TITLE
ts @ run -u no longer triggers on changed files

### ISSUE THREAD

**Issue by bitfabrikken** [dbankier/TiShadow#521]
I'm used to running with "ts @ run -u", which then auto-uploads and reloads TiShadow, when a change is detected in whatever file(s) I'm working on. 

It doesn't seem to detect changes any longer, when I change something and hit save.

It does work to ctrl+c the command and run it again (ts @ run -u)

Any ideas?

**Comment by bitfabrikken** [comment]
TiShadow 2.9.0 both app and server

**Comment by cubico** [comment]
Same problem with same versions executing **ti build -p android -T devive --shadow** on MacOS (El Capitan):

```
[ERROR] TiHTTPClient: (TiHttpClient-1) [28,3965] HTTP Error (java.net.ConnectException): failed to connect to /127.0.0.1 (port 3000): connect failed: ECONNREFUSED (Connection refused)
[ERROR] TiHTTPClient: java.net.ConnectException: failed to connect to /127.0.0.1 (port 3000): connect failed: ECONNREFUSED (Connection refused)
[ERROR] TiHTTPClient: 	at libcore.io.IoBridge.connect(IoBridge.java:124)
[ERROR] TiHTTPClient: 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
[ERROR] TiHTTPClient: 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
[ERROR] TiHTTPClient: 	at java.net.Socket.connect(Socket.java:882)
[ERROR] TiHTTPClient: 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:139)
[ERROR] TiHTTPClient: 	at com.android.okhttp.Connection.connect(Connection.java:148)
[ERROR] TiHTTPClient: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
[ERROR] TiHTTPClient: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
[ERROR] TiHTTPClient: 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
{
[ERROR] TiHTTPClient: 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
[ERROR] TiHTTPClient: 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:491)
[ERROR] TiHTTPClient: 	at ti.modules.titanium.network.TiHTTPClient$ClientRunnable.run(TiHTTPClient.java:1175)
[ERROR] TiHTTPClient: 	at java.lang.Thread.run(Thread.java:818)
[ERROR] TiHTTPClient: Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
[ERROR] TiHTTPClient: 	at libcore.io.Posix.connect(Native Method)
[ERROR] TiHTTPClient: 	at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
[ERROR] TiHTTPClient: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
[ERROR] TiHTTPClient: 	at libcore.io.IoBridge.connect(IoBridge.java:122)
[ERROR] TiHTTPClient: 	... 12 more
```

**Comment by bitfabrikken** [comment]
@dbankier this is one of the core features of TiShadow, and I miss it very much and my productivity has greatly decreased. Do you have any idea what could be happening? Disregard cubico's post above.

**Comment by dbankier** [comment]
"Works for me".  Check your "ts config" that you are not binding to a bad
network interface.

**Comment by bitfabrikken** [comment]
ts config outputs this

```
{
    "useAppcCLI": true,
    "isWatching": false
}
```

how can I set isWatching to true?

**Comment by cubico** [comment]
@bitfabrikken tishadow generates `~/.tishadow.json`. You can update this content.

**Comment by bitfabrikken** [comment]
@dbankier + @cubico 
Setting isWatching to true did nothing. And there's no info about network interfaces with "ts config".

File changes/saves are not detected in realtime - Changing and saving a .js file in the project, would send and update in the tishadow app (1 file(s) bundled).
To do this now, I must manually run "ts @ run -u" every time I want to push the changed files to the tishadow app.
So somehow the detection mecanism for changed files doesn't detect file changes..

**Comment by dbankier** [comment]
forget that config setting - that is for something else.
Basic questions first:  OS? Buidling to which device? Most importantly, how are you installing ts? npm link or install? Worst case, you could always roll back to a previous version...

**Comment by bitfabrikken** [comment]
@dbankier 
Windows 10, 64 bit, building to devices mostly, but also have the ts app running on ios simulator + device.
Installed ts via console (start -> run -> cmd) as administrator: npm install -g tishadow (output pasted below)
I run the server in Titanium's built in console by using 'ts server' and whatever project I'm working on, I go to that directory and type 'ts @ run -u'.
It just does not detect any changes to my projects' files, until I ctrl+c and type 'ts @ run -u' again.

**Comment by bitfabrikken** [comment]
I've just tried rolling back via 'npm install -g tishadow@2.8.2' and this version does detect file changes when 'ts @ run -u' is running :)

**Comment by dbankier** [comment]
Ahhh!!! ***Windows*** Ok there is a chokidar bug (which we switched to from gaze) when trying to watch non-existant directories. The `ready` event is not callled. . I just replicated the issue and fixed it. It is if you are using a non-Alloy or pre-Alloy 1.8 and `i18n` folder does not exists.

Fix and new version on the way
