### ISSUE TITLE
Toasts on Windows 10

### ISSUE THREAD

**Issue by bitfabrikken** [dbankier/TiShadow#522]
I see now in TiShadow 2.9.0 that using Ti.API.error() also shows the errors in a toast notification in bottom right corner in Windows 10. Pretty cool!

Is there any way to disable that?

**Comment by bitfabrikken** [comment]
Found a temporary fix to disable ALL toast notifications on Windows 10. It works, but would be lovely to be able to turn it off for just TiShadow.

https://msdn.microsoft.com/en-us/library/jj980396(v=winembedded.81).aspx

**Comment by yomybaby** [comment]
OK, I'll consider to add a config option for it. :)

**Comment by bitfabrikken** [comment]
@yomybaby I can do it, just tell me where abouts in the code the toast is called :)

**Comment by anik786** [comment]
+1 

Whats the progress on this. It's really irritating me as the error message doesn't show up properly (e.g. showing "\n" instead of doing a line break) and disappearing too quickly to even read and no way to bring it back up.

**Comment by yomybaby** [comment]
I added "errorNotification" option to `ts config` and updated Readme.md
**Now `disabled` is default.**
If you want to enable `errorNotification`, run `ts config -e`.

**Comment by anik786** [comment]
Great thanks!
