### ISSUE TITLE
TiShadow wont install correctly

### ISSUE THREAD

**Issue by Bertuzb** [dbankier/TiShadow#525]
See screenshot below. Something goes wrong with `node cli/tishadow express`

```
npm ERR! Failed at the tishadow@2.9.0 postinstall script 'node cli/tishadow express'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tishadow package,
npm ERR! not with npm itself.
```
Running: Node `4.6.2`, npm `4.1.2`

![schermafbeelding 2017-03-07 om 15 12 13](https://cloud.githubusercontent.com/assets/10498595/23660087/91e9dd68-0348-11e7-94b6-21a3124578f7.png)

**Comment by Bertuzb** [comment]
running `npm install -g titanium` fixed the issue. Im using `appc ti` commands to build the app but I'm getting various generic errors including `Alloy Compile Error`.

**Comment by Bertuzb** [comment]
update: this package does not seem to support `appc` commands, you _must_ build with `titanium build` and have `titanium` and `alloy` globally installed. If you have installed those, it will work.

I'm hereby putting a feature request for supporting `appc alloy` and `appc titanium` modules which seem to be nested under the `appcelerator` module

**Comment by dbankier** [comment]
See this: https://github.com/dbankier/TiShadow#using-the-appcelerator-cli
