### ISSUE TITLE
After update socket.io, app can't connect to TiShadow server.

### ISSUE THREAD

**Issue by yomybaby** [dbankier/TiShadow#532]
After  5164e9433387ccded47beae98e5da372b47b2518 commit, app can't connect to TiShadow server. Before 5164e9433387ccded47beae98e5da372b47b2518 commit, it work properly.

5164e9433387ccded47beae98e5da372b47b2518 needs more test? or is there  something that I miss?

**Comment by dbankier** [comment]
Did you update the app as well?

**Comment by yomybaby** [comment]
### What I did
Yes. Rerun appify and restart server.
I tested on iOS simulator below:
- In 5164e9433387ccded47beae98e5da372b47b2518, rerun appify and restart server : can't connect
- In c73318039eef683a9d3889a90c2a4f9a221a7cfb, rerun appify and restart server : can connect

### Env
Xcode 8.3.1,  macOS 10.12.3, Node 6.9.4, Ti 6.0.3.GA, also add below code to trap.xml
```
 <dict>
  <key>NSAllowsArbitraryLoads</key><true/>
</dict>
```

**Comment by dbankier** [comment]
hmmm... I'm testing on iOS sim too. It wasn't working initially until I updated all the client side socket.io. Was the appify a clean build?

**Comment by yomybaby** [comment]
Yes! 
- delete appify app on iOS sim.
- `ti clean`
- `ti build -p ios --appify`

**Comment by dbankier** [comment]
hmm... reinstalled the node_modules on the server side?

**Comment by yomybaby** [comment]
Oops. I forgot to `nom install` because I use Tishadow with `npm link`.
I'll try again now and let you know.

**Comment by yomybaby** [comment]
Sorry for my mistake.
Now it connected, but `ts @ run` have an below error. (`ts run` is okey)
```
/Users/yomybaby/Documents/TiWorkspace/_tools/TiShadow/cli/support/api.js:20
    connected_socket.socket.reconnect();
                           ^

TypeError: Cannot read property 'reconnect' of undefined
    at postToServer (/Users/yomybaby/Documents/TiWorkspace/_tools/TiShadow/cli/support/api.js:20:28)
    at Object.exports.newBundle (/Users/yomybaby/Documents/TiWorkspace/_tools/TiShadow/cli/support/api.js:80:3)
    at WriteStream.<anonymous> (/Users/yomybaby/Documents/TiWorkspace/_tools/TiShadow/cli/support/compiler.js:86:11)
    at emitNone (events.js:91:20)
    at WriteStream.emit (events.js:185:7)
    at fs.js:2037:14
    at /Users/yomybaby/Documents/TiWorkspace/_tools/TiShadow/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:43:10
    at /Users/yomybaby/Documents/TiWorkspace/_tools/TiShadow/node_modules/archiver-utils/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by dbankier** [comment]
did you update all the node modules? the socket.io-client is also updated.

**Comment by dbankier** [comment]
Just saw your new error when running it with JAST, but not using `ts @ run -u`. Looking at it now.

**Comment by dbankier** [comment]
Just removing that line fixes it.

**Comment by yomybaby** [comment]
Thanks!
