### ISSUE TITLE
Feature: Support ES6

### ISSUE THREAD

**Issue by gaspardle** [dbankier/TiShadow#535]
We can use ES6 with Titanium 6.1.0 and Alloy 1.10 but currently TiShadow doesn't seem to support it.

http://docs.appcelerator.com/platform/latest/#!/guide/ES6_in_Titanium_SDK_6.1.0

 We could use Babel or use uglify-es instead of uglifyjs.

**Comment by dbankier** [comment]
Have a look at https://github.com/dbankier/JAST. I use this very every app I build. It mashes TiShadow with babel (for ES6), jade for views and stss for styles tied together using Grunt.

**Comment by gaspardle** [comment]
It may not the best way but this works for me.

https://github.com/gaspardle/TiShadow/commit/a35d2af290c04b9ab870317a86bb68ee285d3b50

**Comment by dbankier** [comment]
ts now support the the transpile option (https://www.appcelerator.com/blog/2018/06/using-es6-in-a-titanium-app/)

closed with 2ce78dbd8382b131ee726e5940ab272f57363f55
