### ISSUE TITLE
Accessing model/collection/database not working in tishadow

### ISSUE THREAD

**Issue by icecandy** [dbankier/TiShadow#536]
I am working on a project which runs fine as a straight ti build to ios. In tishadow at a certain point in the app it crashes with the following error:
[ERROR] [ipad, 10.0, 192.168.0.11] 
Type: Error
Message: invalid SQL statement
File: /iphone/alloy/models/AchievementRewards.js.js
Line: 72
[ERROR] [ipad, 10.0, 192.168.0.11] {
  "message": "undefined is not an object (evaluating '__p.require(\"alloy/models/\" + ucfirst(name)).Collection')",
  "line": 240,
  "column": 61,
  "stack": "createCollection\nController\ncreateController\nviewCreation\nrowSelect\n"
}

It is obviously a problem with accessing a Model/Collection/SQL. Not sure why it references a file called AchievementRewards.js.js when the model file is AchievementRewards.js

I have just updated tishadow to 2.9.2, although it didn't work on 2.9.0 either. I am running Ti SDK 6.1.1.

I have spent some time Googling this but can't find anything. Any ideas?

**Comment by dbankier** [comment]
Can you share the SQL statement, I think ts is mangling it.

**Comment by icecandy** [comment]
Well unfortunately, it was a while ago and I'm not working for that company any more so I can't easily run the project again and can't remember the SQL.

However I have another problem since updating to tishadow 2.9 as well. I'll create another ticket.
