### ISSUE TITLE
Alloy Compile Error

### ISSUE THREAD

**Issue by icecandy** [dbankier/TiShadow#538]
Another problem with version 2.9.2.  I have recently reinstalled my system so all ti stuff is freshly installed.
Compiling an ios project to the simulator works fine. This is using Ti SDK 5.5.1.
$ appc ti build -p ios --target simulator --device-id 5D78C1DE-0935-4D30-A05E-A62A3C7A2315

If I run tishadow I get:-
$ tishadow run
[INFO] Beginning Build Process
[INFO] Compiling Alloy for android
[ERROR] Alloy Compile Error
This is for ios and android. No other errors - just an instant stop - so no clues to follow up.

Any ideas?

**Comment by dbankier** [comment]
Looks like an issue with the alloy compilation and not ts.

**Comment by icecandy** [comment]
This is not an alloy compilation problem. I now have a completely new trivial Ti example project. it compiles fine and runs on the simulator on iOS and Android.
Same problem with tishadow run...instant "[ERROR] Alloy Compile Error" problem.

**Comment by icecandy** [comment]
Seems to be a mismatch between ti and appc ti. "ts config --use-appc-CLI" fixes it.
It would help to have some feedback :)
