### ISSUE TITLE
working without alloy

### ISSUE THREAD

**Issue by farfromrefug** [dbankier/TiShadow#542]
Hi,
I am looking at tishadow, but my environment is a little special.
First i dont use alloy.
Looking at the code it seems that you look in ```app``` folder to see file changes and stuff. Is that correct? How do you handle non alloy project? (your website seems to mention that it should work).

Now to go further, i actually don't use Appcelerator framework, but my own fork.
I won't go through all the differences, but the main 2 considering tishadow is that my fork already support babel/typescript.
The thing is that a ```ti build``` is necessary to rebuild the typescript files and the javascript files. Those files are then moved inside the build project and the build process (the normal one) picks up those files to build the app package.
Do you think i could integrate your tishadow with it? By that i mean configure tishadow to:
- look for changes in my resources folder (custom filetype extensions like ts, js, and even more that i use for template like tss but not tsss)
- build with ```ti build```
- pick up modified files the build folder and send them to the tishadow server?

Thanks

**Comment by dbankier** [comment]
tishadow was built to work watching the Resources folder before Alloy came along.
I still have some old non-Alloy projects that I use tishadow for. TiShadow watches the Resources folder and will push any changed files. If you want to manipulate a file before it hits the Resources folder, then use some thing else to that. You can say how I have done it with something like https://github.com/dbankier/JAST.
