### ISSUE TITLE
Can't build using --appify on latest 7.3.0 SDK

### ISSUE THREAD

**Issue by miniman42** [dbankier/TiShadow#545]
Build now fails with error
`
...
[INFO]  App thinning disabled, skipping asset image sets
[INFO]  Processing JavaScript files
[ERROR] /Users/.../workspaces/appcelerator/Project/build/appify/Resources/lib/should.js: Property key of ObjectMethod expected node to be of a type ["Identifier","StringLiteral","NumericLiteral"] but instead got "BinaryExpression"
`

**Comment by miniman42** [comment]
Same error on iOS and Android builds.  Any idea how to fix this? Thanks!

**Comment by miniman42** [comment]
@dbankier Sorry to poke, but would really appreciate a dig out on this.  Liveview doesn't come close to tishadow!

**Comment by dbankier** [comment]
7.3.0 isn't GA yet. I will check it once released.

**Comment by miniman42** [comment]
Whoop @dbankier ! They've just released 7.3.0.GA - much appreciate your support on this. I've wasted so much time without tishadow!

**Comment by spbroom** [comment]
Same error here, looking forward to fix, really need it! thanks @dbankier

**Comment by dbankier** [comment]
hmmm... just worked with a classic project.
Is your issue with an alloy project?

**Comment by dbankier** [comment]
Alloy project also worked (with the `--shadow` flag). 
I need a few more details.

**Comment by miniman42** [comment]
Curious, my project is alloy yeah, and has a number of custom modules...  I’ll try the shadow flag, but I can say all works perfectly using —appify if I set SDK to 7.1.1.GA and breaks when I set it to 7.3.0.GA

**Comment by miniman42** [comment]
Ok so just tried to build for ios simulator out of curiousity and that works, but device builds for android and ios both fail

**Comment by miniman42** [comment]
I can also confirm that creating a brand new project ie. `appc new -t titanium` and then running `appc ti build -p ios -T device --appify`on the test project (using a wildcard ios cert) fails with same error
`[ERROR] /..../workspaces/adhoc/tistest/build/appify/Resources/lib/should.js: Property key of ObjectMethod expected node to be of a type ["Identifier","StringLiteral","NumericLiteral"] but instead got "BinaryExpression"`

**Comment by dbankier** [comment]
Are you using an extra babel hooks or configs?

**Comment by miniman42** [comment]
Nope - nothing!

**Comment by dbankier** [comment]
hmmm... it is babel error

**Comment by miniman42** [comment]
Can you reproduce now?

**Comment by dbankier** [comment]
not yet

**Comment by miniman42** [comment]
OK so my versions of stuff in case this is the issue:
I've a custom 7.3.0 and a 7.3.0.GA - All comments here relate to the GA - but i do notice there are a couple of different versions of node-appc hanging around below...

$ appc info
Appcelerator Command-Line Interface, version 7.0.5
Copyright (c) 2014-2018, Appcelerator, Inc.  All Rights Reserved.

Operating System
  Name                        = Mac OS X
  Version                     = 10.13.6
  Architecture                = 64bit
  # CPUs                      = 8
  Memory                      = 16.0GB

Node.js
  Node.js Version             = 8.5.0
  npm Version                 = 6.2.0

Appcelerator CLI
  Installer                   = 4.2.13
  Core Package                = 7.0.5

Titanium CLI
  CLI Version                 = 5.1.1
  node-appc Version           = 0.2.44

Titanium SDKs
  7.3.0.GA
    Version                   = 7.3.0
    Install Location          = /Users/…/Library/Application Support/Titanium/mobilesdk/osx/7.3.0.GA
    Platforms                 = iphone, android
    git Hash                  = 35af917
    git Timestamp             = 8/16/2018 23:01
    node-appc Version         = 0.2.45
  7.3.0
    Version                   = 7.3.0
    Install Location          = /Users/…/Library/Application Support/Titanium/mobilesdk/osx/7.3.0
    Platforms                 = android, iphone
    git Hash                  = 27c183d792
    git Timestamp             = 8/8/2018 16:35
    node-appc Version         = 0.2.48

**Comment by miniman42** [comment]
What else should I try?

**Comment by miniman42** [comment]
Is it not weird that it only fails for device builds (both ios and android)? ie sim works fine?

**Comment by dbankier** [comment]
replicated. looking into it now.

**Comment by dbankier** [comment]
fix with this: https://github.com/dbankier/TiShadow/commit/cf5ea9ffabfb598a3174d9bfb5f8a1e411329618
new version being to pushed to npm now  `2.9.5`

**Comment by miniman42** [comment]
great thanks @dbankier - I'll grab it as soon as it's available, much appreciated! 👍
