### ISSUE TITLE
Does not compile with Titanium SDK v7.3.0GA 

### ISSUE THREAD

**Issue by anik786** [dbankier/TiShadow#546]
When compiling using the latest version of Titanium: v7.3.0 for Android, I get the following error:

> [ERROR] C:/Users/yahya/Documents/apps/tishadowapp/Resources/lib/should.js: Property key of ObjectMethod expected node to be of a type ["Identifier","StringLiteral","NumericLiteral"] but instead got "BinaryExpression"

I didn't test this on iOS, but I assume the same issue would occur.

Note there is no problem with v7.2

**Comment by dbankier** [comment]
Update to the latest version of tishadow

**Comment by anik786** [comment]
Thanks the new update solved the issue.
Can we also make the upgrade command actually say if the application is upgrading, as currently it always says "Upgrdaing App..." regardless if a new update is done or not. Hence I do not know if I should re-compile.
