### ISSUE TITLE
Now working with Titanium SDK 7.3.0 on iOS due to use of removed API's

### ISSUE THREAD

**Issue by anik786** [dbankier/TiShadow#547]
The ios version of TiShadow compiles but does not run due to the use of removed namespaces:

```
Titanium.UI.iPhone
Ti.UI.iPhone
```

Majority of the cases you would now use:

```
Titanium.UI.iOS
Ti.UI.iOS
```

so it should be some quick fixes.

**Comment by dbankier** [comment]
Ahhh.. you are using the container app. Should be a quick fix.

**Comment by anik786** [comment]
Thanks. 
Out of curiosity, your comment suggests there is another way of running TiShadow without the container app? Is that the case?

**Comment by dbankier** [comment]
https://github.com/dbankier/TiShadow#new-dummys-path-tishadow-express

**Comment by anik786** [comment]
Cool. Tell us once the issue is fixed. Thanks :-)

**Comment by dbankier** [comment]
That was fixed with d6d8822e888bf5447b3ffb23937bc4344c5389f9 a while back.
