### ISSUE TITLE
Another process is currently bound to port xxxx show stopper

### ISSUE THREAD

**Issue by icecandy** [dbankier/TiShadow#548]
I've been using tishadow for quite a while and generally works fine. I have a specific problem in a special circumstance which stops all ti compilation (not just tishadow).
So compiling with express using the tishadow flag and the following at cli this works fine:
$ appc ti build -p ios --target simulator --device-id A88F7442-E023-4B1E-8646-B3196EDC8285 --shadow --host 192.168.0.4
Now if I change my internet connection - I have one fibre broadband service connected with ethernet and ip address 192.168.0.4 which sometimes goes down and so have to switch to a second service on wi-fi with ip address 192.168.1.15 - everything stops working. Even the standard ti compile without tishadow. So:
$ appc ti build -p ios --target simulator --device-id A88F7442-E023-4B1E-8646-B3196EDC8285 --shadow --host 192.168.1.15
does not work and:
$ appc ti build -p ios --target simulator --device-id A88F7442-E023-4B1E-8646-B3196EDC8285
does not work.
I get the error:
[DEBUG] Checking if log server port 46035 is available
[DEBUG] Log server port 46035 is in use, testing if it's the app we're building
[ERROR] Another process is currently bound to port 46035
[ERROR] Set a unique <log-server-port> between 1024 and 65535 in the <ios> section of the tiapp.xml
I have tried quitting the simulator, quitting the terminal and doing a hard restart (shut down and restart) and nothing changes. If changing the port number worked I could do that but I don't know which ports are being used to find one which isn't (a shot in the dark process). I spoke to Hans @Axway/Appcelerator and he reckoned it was a problem with tishadow.
Any idea why this happens and how to fix it?

**Comment by dbankier** [comment]
This is nothing to do with TiShadow. It is an annoying Appcelerator issue, with a simple work around.

See, e.g. 
https://jira.appcelerator.org/browse/TIMOB-24034
https://jira.appcelerator.org/browse/TIMOB-25872

Use something like this is your ios section of tiapp.
`<log-server-port>12345</log-server-port>`

/cc @hansemannn

**Comment by icecandy** [comment]
I thought I'd get the buck passed around :(
I'd seen those JIRA entries, but @hansemannn was adamant it was a tishadow thing.
Can't win!
