### ISSUE TITLE
TiShadow does not work with Alloy Themes

### ISSUE THREAD

**Issue by R4mpancy** [dbankier/TiShadow#550]
I make heavy use of Alloy's Themes in my main app, so that I can distribute multiple copies of differently styled apps on the same codebase.

I wanted to adopt TiShadow as a tool that would greatly aid in testing however, I notice that when building with TiShadow and running the app that none of the Theme assets seem to carry over. It's as if I had built the app with no theme or the default. 

Is there something else I may be missing or is this currently not a capability of TiShadow?

**Comment by dbankier** [comment]
hmmm.... I use alloy themes heavily too and it works for me. What error are you getting?

**Comment by dbankier** [comment]
Sorry closing this. I need more details.
