### ISSUE TITLE
Error when including the Firebase SDK

### ISSUE THREAD

**Issue by caspahouzer** [dbankier/TiShadow#553]
Hi,

I've included the Firebase SDK from https://github.com/hansemannn/titanium-firebase

I've put the configuration files in `Resources/iphone/GoogleService-Info.plist` and `Resources/android/google-services.json`

On starting the app with tishadow, I got an error

```
[DEBUG] [iphone, 12.1, 10.55.15.25] Native module:firebase.core
[DEBUG] [iphone, 12.1, 10.55.15.25] Native module:firebase.analytics
[ERROR] [iphone, 12.1, 10.55.15.25] Error: `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) could not find a valid GoogleService-Info.plist in your project. Please download one from https://console.firebase.google.com/.
```

Building the app with Axway Studio, works fine as expected. What can I do?

**Comment by dbankier** [comment]
I think it is a matter of those files being (or moved to) the Resources directory of the appified (/container) app.

**Comment by caspahouzer** [comment]
Same behavior, when added to Resources root. Studio works, shadow doesn't.
Maybe it's even not copied?
