### ISSUE TITLE
Cannot run --appify with SDK 8.0.X

### ISSUE THREAD

**Issue by miniman42** [dbankier/TiShadow#554]
Latest SDK's dont seem to work with Tishadow and appify. If trace is enabled we get
```
[TRACE] Undefined symbols for architecture x86_64:
[TRACE]   "_deflate", referenced from:
[TRACE]       _zipWriteInFileInZip in libti.compression.a(zip.o)
[TRACE]       _zipCloseFileInZipRaw in libti.compression.a(zip.o)
[TRACE]   "_deflateInit2_", referenced from:
[TRACE]       _zipOpenNewFileInZip3 in libti.compression.a(zip.o)
[TRACE]   "_deflateEnd", referenced from:
[TRACE]       _zipCloseFileInZipRaw in libti.compression.a(zip.o)
[TRACE]   "_inflateInit2_", referenced from:
[TRACE]       _unzOpenCurrentFile3 in libti.compression.a(unzip.o)
[TRACE]   "_inflateEnd", referenced from:
[TRACE]       _unzCloseCurrentFile in libti.compression.a(unzip.o)
[TRACE]   "_crc32", referenced from:
[TRACE]       -[TiCompressionZipArchive addFileToZip:newname:] in libti.compression.a(ZipArchive.o)
[TRACE]       _unzReadCurrentFile in libti.compression.a(unzip.o)
[TRACE]       _zipWriteInFileInZip in libti.compression.a(zip.o)
[TRACE]   "_inflate", referenced from:
[TRACE]       _unzReadCurrentFile in libti.compression.a(unzip.o)
[TRACE]   "_get_crc_table", referenced from:
[TRACE]       _unzOpenCurrentFile3 in libti.compression.a(unzip.o)
[TRACE]       _zipOpenNewFileInZip3 in libti.compression.a(zip.o)
[TRACE]   "_utf8_nextCharSafeBody", referenced from:
[TRACE]       -[SRWebSocket _innerPumpScanner] in libnet.iamyellow.tiws.a(SRWebSocket.o)
[TRACE] ld: symbol(s) not found for architecture x86_64
[TRACE] clang: error: linker command failed with exit code 1 (use -v to see invocation)```

Is this easily fixed? Any help would be much appreciated!

Thx.

**Comment by miniman42** [comment]
@dbankier Is this possibly to do with the inclusion of the TiCore as a framework now in SDK 8.0.X?? Perhaps the wrapper project needs to be updated?

**Comment by miniman42** [comment]
This looks similar... https://github.com/appcelerator-modules/ti.compression/issues/21

**Comment by dbankier** [comment]
Just a module update. Testing now and will push a new version soon.

**Comment by dbankier** [comment]
fixed.

**Comment by miniman42** [comment]
Thanks @dbankier - Works in the Sim, but now has an issue with a real device...
 ```appc ti build -p ios -T device --appify```

[ERROR] 2019-05-20 13:49:51.930 xcodebuild[2235:15990]  DTDeviceKit: deviceType from 00008006-001243C91EA2002E was NULL
[ERROR] 2019-05-20 13:49:51.930 xcodebuild[2235:15990]  DTDeviceKit: deviceType from 00008006-001243C91EA2002E was NULL
[ERROR] 2019-05-20 13:49:51.932 xcodebuild[2235:15990]  iPhoneSupport: 📱<DVTiOSDevice (0x7f80074ebac0), My-iPhoneX, iPhone, 12.2 (16E227), fca...f39> unable to mount DeveloperDiskImage (Error Domain=com.apple.dtdevicekit Code=601 "Could not find platform" UserInfo={NSLocalizedDescription=Could not find platform})
[ERROR] 2019-05-20 13:49:52.038 xcodebuild[2235:15988] [MT] DTDeviceKit: deviceType from 00008006-001243C91EA2002E was NULL
[ERROR] 2019-05-20 13:49:52.048 xcodebuild[2235:15988] [MT] DTDeviceKit: deviceType from 00008006-001243C91EA2002E was NULL
[ERROR] 2019-05-20 13:49:52.172 xcodebuild[2235:15988] [MT] DTDeviceKit: deviceType from 00008006-001243C91EA2002E was NULL
[ERROR] 2019-05-20 13:49:52.179 xcodebuild[2235:15988] [MT] DTDeviceKit: deviceType from 00008006-001243C91EA2002E was NULL
[ERROR] ** BUILD FAILED **
[ERROR] The following build commands failed:
[ERROR]         CompileC /Users/me/Documents/Work/Stuff/workspaces/appcelerator/MyApp/build/appify/build/iphone/build/Intermediates/MyApp.build/Debug-iphoneos/MyApp.build/Objects-normal/armv7/MediaModule.o /Users/me/Documents/Work/Stuff/workspaces/appcelerator/MyApp/build/appify/build/iphone/Classes/MediaModule.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[ERROR] (1 failure)

**Comment by miniman42** [comment]
Looks similar : https://github.com/appcelerator-modules/ti.nfc/issues/26

**Comment by dbankier** [comment]
Yep. I noticed that with 8.0.1.GA also. Looks like an issue with the SDK itself. If you don't need the media module than just comment out these lines (https://github.com/dbankier/TiShadow/blob/master/app/Resources/api/Includes.js#L70-L85) the moment or use a different SDK version 

I think it needs to be raise with AppC

**Comment by miniman42** [comment]
Hrm... I do need the videoplayer, so commenting is not gonna work for me.  Also 8.0.1 is the first SDK to fix the many crashes we've experienced since 7.3/4...   Any pointer as to why it why it's only an issue when using shadow? Not sure how to raise it with the Appc and actually make sense to them :)

**Comment by dbankier** [comment]
No idea. Does it build without `ts`? The build error is with the `MediaModule.m` which is part of the SDK...

**Comment by miniman42** [comment]
Yeah it builds just fine without ```ts``` for sim and device - also builds fine with ```ts``` for the sim - Just does not work when targeting an attached device with ```ts```

**Comment by dbankier** [comment]
Just released a new version that works around the issue.
Here is the jira issue if you are curious: https://jira.appcelerator.org/browse/AC-6261

**Comment by miniman42** [comment]
Thanks @dbankier - workaround works like a charm for me. I'll keep an eye on the ticket as I maintain a custom  SDK branch
