### ISSUE TITLE
[Android] build fails on Ti SDK 9 cause of new gradle system.

### ISSUE THREAD

**Issue by Astrovic** [dbankier/TiShadow#568]
In order to continue using TiShadow on Android with TiSDK>9, it would be necessary to update to use gradle.

**Comment by dbankier** [comment]
Thanks. Will hopefully look into it soon.

**Comment by dbankier** [comment]
Is there a post anywhere for 9.0 migration?

**Comment by Astrovic** [comment]
Thanks 👍 
This is for general android module migration: https://wiki.appcelerator.org/display/guides2/Android+Module+Upgrade+Guide#AndroidModuleUpgradeGuide-MigrationtoSDK9.0.0

**Comment by dbankier** [comment]
Got it. Already updated the native modules.
Working on updating the node packages, it has been a long time since that
was done. The min-node version is still 0.12.
Might take bit of time.

**Comment by Astrovic** [comment]
Ok, thanks a lot for your support!  I love TiShadow, I always preferred it to liveview.

**Comment by dbankier** [comment]
All fixed. Currently can be installed with `npm install tishadow@next`. Code changes currently on the `ti_9` branch.
