### ISSUE TITLE
Preloading a SQLite database file for an Alloy model failes

### ISSUE THREAD

**Issue by FokkeZB** [dbankier/TiShadow#78]
The following Alloy model:

```
exports.definition = {
    config: {
        columns: {
            'id': 'INTEGER PRIMARY KEY AUTOINCREMENT',
            'text': 'STRING'
        },
        adapter: {
            type: "sql",
            collection_name: "card",
            db_name: 'data',
            db_file: 'data.sqlite',
            idAttribute: 'id'
        }
    }
}
```

gives:

```
[ERROR] [ipad, 5.1.1, 192.168.0.100] 
Type: Error
Message: invalid database install path
File: /alloy/models/Card.js
Line: 251
```

But works on iPad.

I'm sure it has something to do with the difference between regular app paths and paths in TiShadow. I guess we'll have to override some Alloy method, e.g. `alloy/sync/sql.js`

**Comment by pmcheng99** [comment]
Hi
I still have the same problem.
11:12:28 [DEBUG] [ipad, 8.1, 192.168.11.8] Database Initial start!
11:12:28 [DEBUG] [ipad, 8.1, 192.168.11.8] privateDir:file:///Users/foxconn/Library/Developer/CoreSimulator/Devices/4073FB5B-C778-4764-9B45-F839A69C4AB7/data/Containers/Data/Application/D4B83303-EA23-4FA6-94F1-126AEE0F85A6/Library/Private%20Documents/
11:12:28 [DEBUG] [ipad, 8.1, 192.168.11.8] Native module:com.gds.shc.Database
11:12:28 [DEBUG] [ipad, 8.1, 192.168.11.8] Native module:com.gds.shc.Database
11:12:28 [ERROR] [ipad, 8.1, 192.168.11.8] Error: Could not retrieve attributes
11:12:28 [INFO] [ipad, 8.1, 192.168.11.8] DrPad launched.
Could anyone help me to solve this? Thanks a lot.
